### PR TITLE
.github/workflows: Add job to merge staging to stable

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

First commit:
If all tests pass on a push, this should move the commits from staging
to stable. This should allow for the default branch to become
'stable' afterwards.

Second commit:
This adds a new job that will start all catalog 'core_merge' workflows
and poll once every 30s for the results. If at least one of them fails
then it will mark it as failed, otherwise all succeeding means a pass.

Test will fail if there are other ongoing catalog 'core_merge'
workflows, to protect again concurrency problems. Rerun if necessary.

After this runs and everything passes, staging is merged into stable.
This runs only on pushes to staging.

### CODE REVIEW

**Review by nderjung — APPROVED** [review]
Were you able to get this to work on the bananatree?

Other than that, looks good.

Reviewed-by: Alexander Jung <alex@unikraft.io>

**Comment by craciunoiuc** [comment]
Didn't try it yet, was about to

Edit: commit 1 now works

**Comment by craciunoiuc** [comment]
commit 2 works on `unikraft-bananatree` https://github.com/unikraft-bananatree/unikraft/actions/runs/8467714976/job/23199080917

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
