### PR TITLE
drivers: Add PLAT_COMMON_BASE to the include path

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

The `PCI` and `virtio` have dependencies on headers under `uk/plat/common`. Add `PLAT_COMMON_BASE` to the include path to prevent compile errors. Moreover, the `virtio-ring` driver includes `virtio/virtio-bus.h`. Add `LIBVIRTIO_BUS_BASE` to this driver library's include path.

### CODE REVIEW

**Review by rares-miculescu — APPROVED** [review]
Everything looks good on my side. Thanks, @michpappas!

Reviewed-by: Rares Miculescu [miculescur@gmail.com](mailto:miculescur@gmail.com)

**Review by mogasergiu — COMMENTED** [review]
LGTM. One minor question: why only `CINCLUDES`? Why not `CXXINCLUDES`/`ASINCLUDES` as well? Either way, I know it's temporary.

**Comment by michpappas** [comment]
> LGTM. One minor question: why only `CINCLUDES`? Why not `CXXINCLUDES`/`ASINCLUDES` as well? Either way, I know it's temporary.

`ASINCLUDES` and `CXXINCLUDES` are only required for headers exported by the library (and `ASINCLUDES` according to @skuenzer only if the libraries exports headers required used by asm). Headers private to the library (`LIBXYZ*INCLUDES`), normally don't need these.

**Comment by mogasergiu** [comment]
> > LGTM. One minor question: why only `CINCLUDES`? Why not `CXXINCLUDES`/`ASINCLUDES` as well? Either way, I know it's temporary.
> 
> `ASINCLUDES` and `CXXINCLUDES` are only required for headers exported by the library (and `ASINCLUDES` according to @skuenzer only if the libraries exports headers required used by asm). Headers private to the library (`LIBXYZ*INCLUDES`), normally don't need these.

I see, so it is assumed a library will never need to import an asm macro?

**Comment by michpappas** [comment]
> > > LGTM. One minor question: why only `CINCLUDES`? Why not `CXXINCLUDES`/`ASINCLUDES` as well? Either way, I know it's temporary.
> > 
> > 
> > `ASINCLUDES` and `CXXINCLUDES` are only required for headers exported by the library (and `ASINCLUDES` according to @skuenzer only if the libraries exports headers required used by asm). Headers private to the library (`LIBXYZ*INCLUDES`), normally don't need these.
> 
> I see, so it is assumed a library will never need to import an asm macro?

I imagine that falls under the convention that says if it needs to then add it. IMO opinion it would be more fail-safe to export / import `ASFLAGS` always, as one not always knows when something will be required to be imported by asm, but then that means that it also requires to add asm include guards in all headers for all declarations that can be grokked by asm and so on. Either way, if you think it's worth enough, I think this topic is more suitable to discuss at the maintainer's level as it's general policy.

**Review by mogasergiu — APPROVED** [review]
> I think this topic is more suitable to discuss at the maintainer's level as it's general policy

Yes, of course, makes sense. We can always change those lines if needed anyway :man_shrugging:.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
