### PR TITLE
lib/{uk9p,9pfs}: 9p2000.L support

### PR DESCRIPTION
**Pull request by dinhngtu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

9p2000.L is a 9pfs protocol variant closely following Linux's filesystem semantics, with several implementations in QEMU, [diod](https://github.com/chaos/diod), kvmtool and so on.

This PR adds 9p2000.L support to Unikraft. It contains implementations of 9p2000.L-specific commands, mount options for choosing a specific protocol version, as well as several related fixes.

### CODE REVIEW

**Review by eduardvintila — COMMENTED** [review]
Greetings, @dinhngtu! The PR is looking great, thanks a lot for your work! I really like your implementation and your overall rigor.

However, I have spotted some mysterious stuff going on regarding the `fsync` 9P2000.L operation. In particular, your implementation of `fsync` seems to be perfectly compatible with the 9P2000.L reference document https://github.com/chaos/diod/blob/master/protocol.md#fsync---flush-any-cached-data-to-disk - it includes in its TFSYNC request only the `fid` of the file to be flushed.

Unfortunately, in the current state, when running an app which uses the `fsync` syscall (such as `app-sqlite`) with the 9P2000.L protocol version selected, this TFSYNC request cannot be decoded by QEMU:

```
[    0.993150] dbg:  [libuk9p] <9p.c @  570> TFSYNC fid 2
[    0.999392] dbg:  [libkvmvirtio] <virtio_ring.c @  361> Old head:0, new head:2, total_desc:2
[    1.006313] dbg:  [libkvmvirtio9p] <virtio_9p.c @  285> notify queue 0
qemu-system-x86_64: Failed to decode VirtFS request type 50
```
Thereby causing the application to hang since a response is never received. Much to my surprise, it actually seems that QEMU's 9p server (and the 9p client from the Linux kernel) implement a somewhat altered version of the `fsync` operation, which is different from the one in the reference specification from the diod project. I have found these particular commits from QEMU and the Linux kernel which introduce an additional parameter to the `TFSYNC` request:

https://github.com/torvalds/linux/commit/b165d60145b717261a0234f989c442c2b68b6ec0
https://github.com/qemu/qemu/commit/49594973fb38283e8c469892fe5eac2942d9bd25

This parameter (`datasync`) seems to be an additional integer which marks whether both the metadata and data or only the data shall be flushed. By adding this integer to the `TFSYNC` request (setting it to 0 marks that the whole file with the metadata is flushed), the `fsync` syscall seems to work now since a response is received after our request:
```
	if ((rc = uk_9preq_write32(req, fid->fid)) || /* fid */
		(rc = uk_9preq_write32(req, 0)) || /* datasync */
		(rc = send_and_wait_no_zc(dev, req)))
		goto out;
```

```
[    3.618283] dbg:  [libuk9p] <9p.c @  570> TFSYNC fid 5
[    3.618458] dbg:  [libkvmvirtio] <virtio_ring.c @  361> Old head:0, new head:2, total_desc:2
[    3.618679] dbg:  [libkvmvirtio9p] <virtio_9p.c @  285> notify queue 0
[    3.620178] dbg:  [libkvmgic] <gic-v2.c @  365> EL1 IRQ#36 caught
[    3.620377] dbg:  [libkvmgic] <gic-v2.c @  365> EL1 IRQ#1023 caught
[    3.620568] dbg:  [libuk9p] <9p.c @  580> RFSYNC  

```

The fact that both QEMU and the Linux kernel simply implement this somewhat different version of the 9P2000.L protocol described in the specification, simply boggles my mind. I don't know the rationale for those commits; I'm really curious of your (and others') take on this.

**Comment by dinhngtu** [comment]
There seems to be a discrepancy between diod's protocol documentation and Linux/QEMU's implementation, I have corrected this. I have also fixed the client implementation of `SETATTR`.

**Review by eduardvintila — APPROVED** [review]
Splendid work, @dinhngtu. Thank you for this PR! No more comments from me!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Comment by dinhngtu** [comment]
Rebased on top of latest staging.

**Pull request closed without merging**
