### PR TITLE
drivers/ukintctlr: Replace libc types with unikraft defined

### PR DESCRIPTION
**Pull request by rares-miculescu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

Some files inside Unikraft use libc data types. This PR changes those data types with Unikraft-specific data types, inside drivers/ukintctlr.

### CODE REVIEW

**Review by RaduNichita — COMMENTED** [review]
Looks good, just fix the commit as mentioned in https://github.com/unikraft/unikraft/pull/1343

**Review by mariasfiraiala — APPROVED** [review]
All well on my side, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Comment by RaduNichita** [comment]
I would put Unikraft with capital U. I will approve after this.

**Review by RaduNichita — APPROVED** [review]
All good.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by michpappas — CHANGES_REQUESTED** [review]
Looks good, https://github.com/unikraft/unikraft/pull/1343#pullrequestreview-1942305875 applies here too.

**Review by michpappas — APPROVED** [review]
Reviewed-by: Michalis Pappas <michalis@unikraft.io>
Approved-by: Michalis Pappas <michalis@unikraft.io>

**Pull request merged**
