### PR TITLE
lib/ukdebug: Use correct variable name for sect-strip.py tool

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBUKDEBUG=y`

### Description of changes

The variable used didn't match the one defined in the platform part and therefore the specified sections were never stripped.

### CODE REVIEW

**Review by RaduNichita — APPROVED** [review]
I tested it and everything works as expected. Thanks, @mschlumpp!

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Comment by marcrittinghaus** [comment]
Hey @mschlumpp,

good catch! After applying the patch I get the following warning from `strip`:
`strip: /unikraft/build/unikraft_linuxu-x86_64.dbg: warning: empty loadable segment detected at vaddr=0x400000, is this intentional?`

The problem is gone for XEN after applying
- https://github.com/unikraft/unikraft/pull/698

Irrespective of this patch, I noticed that the `linuxu` target crashes with a segfault when tracing is enabled.

Any idea?

**Comment by jschlumpp** [comment]
@marcrittinghaus This new warning is the result of the sect-strip.py actually doing something.
The linuxu crash is likely related to the `--omagic` flag, which sometimes produces invalid ELF files.

**Comment by marcrittinghaus** [comment]
> @marcrittinghaus This new warning is the result of the sect-strip.py actually doing something. The linuxu crash is likely related to the `--omagic` flag, which sometimes produces invalid ELF files.

I know that it is due to it now actually doing something. I was wondering, if we can avoid the warning. But it seems at least with #698 to be only a problem for `linuxu` and tracing enabled.

**Comment by jschlumpp** [comment]
Due to the placement of the `.uk_trace_keyvals` the linker seems to be forced to emit a new segment just for that section. However, `strip` doesn't seem to remove that leftover empty segment... I don't think we can do anything to fix that except moving the section for example behind `.rodata`. But doing so will probably leave a gap between `.rodata` and `.data`.

**Review by marcrittinghaus — APPROVED** [review]
Ok, I see. Too bad 😭

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
