### PR TITLE
Skuenzer/ukthreadcb

### PR DESCRIPTION
**Pull request by skuenzer**
Utilizes `uksched` callback mechanism to create and delete pthread-embedded meta data for threads. This enables using pthread-embedded API calls on threads that were created with the native `uksched` API.

Changes v2:
------------
- Rebased to latest staging
- Register init/uninit functions of `uksignal`

### CODE REVIEW

**Comment by skuenzer** [comment]
In order to make pthread-embedded work, please also check out [series 1601 on patchwork](https://patchwork.unikraft.org/project/unikraft/list/?series=1601&state=*).

**Review by danield20 — APPROVED** [review]
Looks good.

Reviewed-by: Daniel Dinca <dincadaniel97@gmail.com>

**Comment by nderjung** [comment]
When this PR was merged, it broke the `staging` branch of Unikraft along with all applications due to the following build error:

```
make: Leaving directory '/tmp/build/80754af9/built/unikraft'
GEN     libsyscall_shim: syscall_map.h.new
GEN     libsyscall_shim: syscall_stubs.h.new
GEN     libsyscall_shim: syscall_nrs.h.newle/s]
GEN     libsyscall_shim: syscall_nrs2.h.newe/s]
GEN     libsyscall_shim: provided_syscalls.h.in.new
CC      libkvmplat: trace.common.o    18file/s]
CC      libkvmplat: traps.isr.o       25file/s]
CC      libkvmplat: cpu_features.common.oile/s]
CC      libkvmplat: cpu_native.common.o5file/s]
AS      libkvmplat: thread_start.common.ofile/s]
CC      libkvmplat: thread.common.o    09file/s]
CC      libkvmplat: sw_ctx.common.o    09file/s]
     7%!▋(MISSING)          13/179 [15.09file/s]/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c: In function 'sw_ctx_size':
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:54:16: error: invalid application of 'sizeof' to incomplete type 'struct ukplat_ctx'
   54 |  return sizeof(struct ukplat_ctx) + arch_extregs_size();
      |                ^~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:55:1: warning: control reaches end of non-void function [-Wreturn-type]
   55 | }
      | ^
make[1]: *** [/tmp/build/80754af9/built/unikraft/support/build/Makefile.build:50: /tmp/build/80754af9/built/apps/helloworld/build/libkvmplat/sw_ctx.common.o] Error 1
make: *** [Makefile:990: sub-make] Error 2
```

**Comment by nderjung** [comment]
This has been addressed in a bux fix #188.

**Pull request closed without merging**
