### PR TITLE
`lib/uksched`, `lib/posix-process`: Feature freeze bugfixes

### PR DESCRIPTION
**Pull request by skuenzer**
This PR contains a number of bugfixes of recently introduced and merged PRs: PR #564 , PR #566

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
I did not manage to reproduce any issues except the `posix-futex` one, but the commits make sense and everything seems to work fine, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by razvand** [comment]
This is OK with me. I will approve once I get a review from @craciunoiuc or @StefanJum .

**Comment by craciunoiuc** [comment]
> This is OK with me. I will approve once I get a review from @craciunoiuc or @StefanJum .

@razvand go home, you are drunk 🥴

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
