### PR TITLE
lib/ukallocbbuddy: fix a memory leak

### PR DESCRIPTION
**Pull request by noureddine-taleb**
@unikraft/maintainers-mem

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

relevant information could be found in this github issue: https://github.com/unikraft/unikraft/issues/688

### CODE REVIEW

**Comment by nderjung** [comment]
Hi @noureddine-taleb! Thank you for this contribution! Please could you add the following `GitHub-Fixes` reference in your commit message (and force-pushing again?) Thanks!

```
GitHub-Fixes: #688
Signed-off-by: ...
```

Also, cc'ing @unikraft/maintainers-mem to have a look at this fix

**Comment by noureddine-taleb** [comment]
done

@unikraft/maintainers-mem

**Comment by flpostolache** [comment]
Hello, @noureddine-taleb . Thank you for submitting this PR. I was looking through the issue points and the second point is a little bit unclear to me. Please correct me if I'm wrong. From my understanding the `memr->nr_pages` should store the number of pages that we have free and can play with. If that is so then the number of pages that we can have in that range would be equal with the formula given [above](https://github.com/unikraft/unikraft/blob/4ef7571e9f4bd7fbfde9bf5e43e5716e2015b386/lib/ukallocbbuddy/bbuddy.c#L428-L435). By directly taking the range and dividing it with the page size, the resulting number would also include the pages needed for the bitmap and memory region structure. This would then add more unnecessary bits to the bitmap and waste one page in some cases when it is not needed. The first point makes sense to me.

**Comment by noureddine-taleb** [comment]
Hi @maniatro111 . so it's a classical checken or egg situation, because to allocate the bitmap we need first to know the amount of available free pages, and the to know the amount of available free pages we need first to allocate the bitmap, so we compromise and allocate the bitmap first using the whole range, as you said that may lead to an extra page wasted in the bitmap in some situations. but this at least gave us the correct number of free pages we can use. in contrast to the old implementation `memr->nr_pages =
		BITS_PER_BYTE * (range - sizeof(*memr)) /
		(BITS_PER_BYTE * __PAGE_SIZE + 1);
`  which correctly calculates the the number of free pages **except it doesn't take into consideration  the following rounding**: `memr_size = round_pgup(sizeof(*memr) + DIV_ROUND_UP(memr->nr_pages, BITS_PER_BYTE));` which reduces the number of free pages even more, in this case relying the calculated `memr->nr_pages` may lead to overflowing into unauthorized memory which is an undefined behavior. in this patch I count the whole range as free, and use it to calculate the bitmap size, and after doing the rounding I subtract the pages taken by the bitmap from the free range: `range -= memr_size;` and ended up with the correct `nr_pages`, plus the new implementation is more readable.

**Review by flpostolache — APPROVED** [review]
Thank you for the explanation. Makes sense now.

Reviewed-by: Florin Postolache <florin.postolache80@gmail.com>

**Review by marcrittinghaus — APPROVED** [review]
Thanks for the fixes @noureddine-taleb!

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
