### PR TITLE
.github/workflows: Add workflow to merge approved PRs

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

Do not merge this yet as governctl was not updated yet.

### CODE REVIEW

**Comment by razvand** [comment]
@craciunoiuc , there was a force push that "added" two extra commits to your PR. Please rebase it.

**Review by skuenzer — APPROVED** [review]
Reviewed-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Reviewed-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Reviewed-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Reviewed-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request merged**
