### PR TITLE
plat/arm64: Fix extregs allocation on Arm

### PR DESCRIPTION
**Pull request by justin-he**
Implement the extregs (currently only fpsimd registers) allocation
related helpers. Otherwise, Unikraft can't be built on Arm kvm plat
due to the missing of several helpers.

Signed-off-by: Jia He <justin.he@arm.com>

### CODE REVIEW

**Comment by nderjung** [comment]
Hey @justin-he! Thanks for submitting these patches via Github! :) Just a few notes on my end:

 * We are working to fix the `arm64-kvm/build` job in the checks below.  This is a [seperate issue](https://github.com/unikraft/kraft/issues/57) currently under investigation.  We hope to get this fixed so your PR can be checked fully by the CI; and,
 * Can you please remove the git trailer `GitHub-Pull-Request:` in your commits messages, this is added automatically by the CI.

Thanks! :)

**Comment by justin-he** [comment]
> * hecked

Thanks, @nderjung  I tested this PR by compiling and running a nginx app on Arm kvm plat.

**Comment by justin-he** [comment]
> Hey @justin-he! Thanks for submitting these patches via Github! :) Just a few notes on my end:
> 
> * We are working to fix the `arm64-kvm/build` job in the checks below.  This is a [seperate issue](https://github.com/unikraft/kraft/issues/57) currently under investigation.  We hope to get this fixed so your PR can be checked fully by the CI; and,
> * Can you please remove the git trailer `GitHub-Pull-Request:` in your commits messages, this is added automatically by the CI.
> 
> Thanks! :)

I have removed the GitHub-Pull-Request line and refined the commit msg.

**Review by razvanvirtan — APPROVED** [review]

**Comment by vladandrew** [comment]
@razvanvirtan Hi Razvan, please add a "reviewed by" in order for the unikraft bot to push these changes. Thanks.

**Comment by razvanvirtan** [comment]
Tested it and everything looks good.

Reviewed-by: Răzvan Vîrtan <virtanrazvan@gmail.com>

**Pull request closed without merging**
