### PR TITLE
drivers/ukbus: Replace libc types with unikraft defined

### PR DESCRIPTION
**Pull request by rares-miculescu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

Some files inside Unikraft use libc data types. This PR changes those data types with Unikraft-specific data types, inside `drivers/ukbus`.

### CODE REVIEW

**Review by RaduNichita — COMMENTED** [review]
Hey @rares-miculescu ,

This looks good to me, but can you fix the commit message failing check? 

Could you also add the reason behind this change, for traceability purposes, please?

**Review by mariasfiraiala — APPROVED** [review]
All good on my side, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by RaduNichita — APPROVED** [review]
All good from my side.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by michpappas — CHANGES_REQUESTED** [review]
Looks good. One change only please in the commit message:
```
for Unikraft to become independent of libc.
```
As it's not be possible for every library to become independent of libc, it would be better to restrict this to the updated subsystem.

**Review by michpappas — APPROVED** [review]
Reviewed-by: Michalis Pappas <michalis@unikraft.io>
Approved-by: Michalis Pappas <michalis@unikraft.io>

**Pull request merged**
