### PR TITLE
support/scripts: Add additional recognised Git trailers to checkpatch

### PR DESCRIPTION
**Pull request by nderjung**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

N/A

### Description of changes

This PR introduces 3 additional Git trailers to be recognised by the checkpatch program:

| Trailer | Purpose |
|---------|---------|
| `GitHub-Fixes` | Used to reference and address an open issue, often a specific bug or problem. GitHub will automatically close the issue once the commit with this Git trailer is merged. |
| `GitHub-Closes` | Used to reference an open issue or PR, which is not specific to a particular bug.  For example, it can be used to supercede another PR.  GitHub will automatically close the referenced issue or PR once a commit with this Git trailer is merged. |
| `Co-authored-by` | Similar to providing additional Signed-off-by's, this trailer is recognised by GitHub and helps attribute authorship, making the user's profile more visible. |
| `Approved-by` | Signifies the authoritive representative (usually a project maintainer) who approved the commit. |

### CODE REVIEW

**Comment by gabrielmocanu** [comment]
All good.

Reviewed-by: Gabi Mocanu <gabi.mocanu98@gmail.com>

**Review by gabrielmocanu — APPROVED** [review]

**Review by RaduNichita — APPROVED** [review]
It looks OK to me, but I didn't found a way to proper test it.  Thanks @nderjung for providing this! :tophat: 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by gabrielmocanu — APPROVED** [review]
I tested with a couple of commits and looks good.

Reviewed-by: Gabi Mocanu <gabi.mocanu98@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
