### PR TITLE
ofw: Fix fdt_get_address, get cell info from parent node.

### PR DESCRIPTION
**Pull request by kubanrob**
### This fixes an error parsing addresses in device trees.

As stated in DT Spec v0.2, section 2.3.5 "#address-cells and #size-cells", the properties `#address-cells` and `#size-cells` need to be read from the parent node, not the node itself. Every parent node is required to have this information in a compliant DT.

While preparing this PR, I found out this patch effectively reverts the function back to its original form in 42c1127.

#### History:
- function intruduced in 42c1127cb4441310f8e4268d0d3b8d011484cdf4
- function updated with non-spec heuristic in libfdt 28fa775d3183d8e3f6d1e164457d5ea6c2a88d52
- libfdt updated, removing the heuristic in 56f86029d6ef681a44af4533a31d7cbb80a6850a

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): amd64
 - Platform(s): kvm, ...
 - Application(s): N/A

### Additional configuration

This problem can be reproduced using an device tree with the following properties for the the GICv3 driver: a correct device tree with `#size-cells` or `#address-cells` properties of the parent different from the default (adress-cells: 2 and size-cells: 1).

### Description of changes

This patch effectively reverts the function back to its original form in 42c1127.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
Nice job, looks good to me.

**Comment by michpappas** [comment]
Hi @kubanrob, I just noticed that this one cause a compiler warning, as the `off` variable is no longer used:
```
/home//mpp/devel/uk_helloworld/unikraft/plat/drivers/ofw/fdt.c: In function 'fdt_get_address':
/home/mpp/devel/uk_helloworld/unikraft/plat/drivers/ofw/fdt.c:255:6: warning: unused variable 'off' [-Wunused-variable]
  255 |  int off = nodeoffset;
```

**Comment by kubanrob** [comment]
> Hi @kubanrob, I just noticed that this one cause a compiler warning, as the `off` variable is no longer used:

Hey @michpappas, the commit renames the `off` variable to `parentoffset` in line 255. Is there any change this is an artifact of merging/cherry-picking while testing.

**Comment by michpappas** [comment]
> > Hi @kubanrob, I just noticed that this one cause a compiler warning, as the `off` variable is no longer used:
> 
> Hey @michpappas, the commit renames the `off` variable to `parentoffset` in line 255. Is there any change this is an artifact of merging/cherry-picking while testing.

Precisely! My bad, sorry 🙂

**Review by razvanvirtan — APPROVED** [review]
All good on my side.

Reviewed-by: Răzvan Vîrtan <virtanrazvan@gmail.com>

**Comment by razvand** [comment]
This is good. Thanks, @kubanrob . @StefanJum , please add your approval + your `...-by` message and I will then finalize the approval for this.

**Review by StefanJum — APPROVED** [review]
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Thanks for this, @kubanrob . It works.

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
