### PR TITLE
lib/posix-unixsocket: Add basic *sockopt support

### PR DESCRIPTION
**Pull request by andreittr**
### Description of changes

This change adds getsockopt/setsockopt support for basic socket options from the SOL_SOCKET family. There are two main types of options added:
- Read-only opts about socket state (e.g. SO_ACCEPTCONN)
- No-op opts for benign unsupported features

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

N/A

### CODE REVIEW

**Comment by John-Ted** [comment]
I checked the supported `getsockopt` options in a basic test based on the catalog `http-c` example (code below).
`SO_ACCEPTCONN` and `SO_TYPE` seem to work, and return proper looking values, however `SO_TYPE` and `SO_DOMAIN` return -1 on the `getsockopt` call and set `errno` to 92 even though they should be supported in the code.

```C
/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2023, Unikraft GmbH and the Unikraft Authors.
 */

#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <errno.h>

#define LISTEN_PORT 8080
static const char reply[] = "HTTP/1.1 200 OK\r\n" \
			    "Content-Type: text/html\r\n" \
			    "Content-Length: 14\r\n" \
			    "Connection: close\r\n" \
			    "\r\n" \
			    "Hello, World!\n";

#define BUFLEN 2048
static char recvbuf[BUFLEN];

int main(int argc __attribute__((unused)),
	 char *argv[] __attribute__((unused)))
{
	int rc = 0;
	int srv, client;
	ssize_t n;
	struct sockaddr_in srv_addr;

	srv = socket(AF_INET, SOCK_STREAM, 0);
	if (srv < 0) {
		fprintf(stderr, "Failed to create socket: %d\n", errno);
		goto out;
	}

	srv_addr.sin_family = AF_INET;
	srv_addr.sin_addr.s_addr = INADDR_ANY;
	srv_addr.sin_port = htons(LISTEN_PORT);

	rc = bind(srv, (struct sockaddr *) &srv_addr, sizeof(srv_addr));
	if (rc < 0) {
		fprintf(stderr, "Failed to bind socket: %d\n", errno);
		goto out;
	}

	int val;
	socklen_t len = sizeof(val);
	
	int ret = getsockopt(srv, SOL_SOCKET, SO_DOMAIN, &val, &len);
	printf("DOMAIN: %d %d %d %d\n", ret, val, AF_UNIX, errno);
	
	ret = getsockopt(srv, SOL_SOCKET, SO_PEEK_OFF, &val, &len);
	printf("PEEK_OFF: %d %d %d\n", ret, val, errno);

	ret = getsockopt(srv, SOL_SOCKET, SO_TYPE, &val, &len);
	printf("TYPE: %d %d %d\n\n", ret, val, errno);
	
	ret = getsockopt(srv, SOL_SOCKET, SO_ACCEPTCONN, &val, &len);
	printf("ACCEPTCONN: %d %d %d\n", ret, val, errno);

	/* Accept one simultaneous connection */
	rc = listen(srv, 1);
	if (rc < 0) {
		fprintf(stderr, "Failed to listen on socket: %d\n", errno);
		goto out;
	}

	ret = getsockopt(srv, SOL_SOCKET, SO_ACCEPTCONN, &val, &len);
	printf("ACCEPTCONN LISTEN: %d %d %d\n", ret, val, errno);

	printf("Listening on port %d...\n", LISTEN_PORT);
	while (1) {
		client = accept(srv, NULL, 0);
		if (client < 0) {
			fprintf(stderr,
				"Failed to accept incoming connection: %d\n",
				errno);
			goto out;
		}

		/* Receive some bytes (ignore errors) */
		read(client, recvbuf, BUFLEN);

		/* Send reply */
		n = write(client, reply, sizeof(reply) - 1);
		if (n < 0)
			fprintf(stderr, "Failed to send a reply\n");
		else
			printf("Sent a reply\n");

		/* Close connection */
		close(client);
	}

out:
	return rc;
}
```

Output:
```
DOMAIN: -1 1206808 1 92
PEEK_OFF: -1 1206808 92
TYPE: 0 1 92

ACCEPTCONN: 0 0 92
ACCEPTCONN LISTEN: 0 1 92
```

**Comment by andreittr** [comment]
> ```c
> srv = socket(AF_INET, SOCK_STREAM, 0);
> ```

I believe with the code above you are testing the sockopt support of INET (i.e. IPv4/6) and not unix domain sockets. These former ones are implemented by an external lib (lwip) and not the core `posix-unixsocket` library, which this PR targets.

In order to use unix domain sockets you need to specify the `AF_UNIX` family when creating the socket(s).

**Review by John-Ted — APPROVED** [review]
Looks good.

Reviewed-by: Ioan-Teodor Teugea ioan_teodor.teugea@stud.acs.upb.ro

**Review by eduardvintila — APPROVED** [review]
Thanks!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Comment by RaduNichita** [comment]
I also checked this during my work and confirm it works!

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
