### PR TITLE
arch/arm64: Use ukarch_random_seed to seed MTE keys

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`arm64`]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

Generating seed values should be done using the ukarch_random_seed interface, as it provides values higher brute-force resistance than numbers generated by the DRBG-based output of ukarch_random.

Use ukarch_random_seed to populate RGSR_EL1.

### CODE REVIEW

**Review by razvanvirtan — COMMENTED** [review]
Hi, @michpappas !
Can you please provide a suggestion for the testing environment? I have been trying qemu 6.2.0 + machine virt + several cpu models (including `max`) and I still don't have MTE2 support on any of them.

**Comment by michpappas** [comment]
Hi @razvanvirtan, MTE support is a machine-specific option in virt: https://qemu.readthedocs.io/en/latest/system/arm/virt.html

You can test with:
```
qemu-system-aarch64 -machine virt,mte=on -cpu max -nographic -kernel build/app-helloworld_kvm-arm64
```

**Review by razvanvirtan — APPROVED** [review]
Sorry, I have initially missed the `mte=on` option.
I tested and it looks good on my side, thank you for this!

Reviewed-by: Razvan Virtan <virtanrazvan@gmail.com>

**Review by marcrittinghaus — APPROVED** [review]
Looks good and makes sense 😃

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
