### PR TITLE
build: Option to treat compiler warnings as errors

### PR DESCRIPTION
**Pull request by skuenzer**
Introduces an option to treat compiler warnings as errors. The build
system stops compilation if a compiler warning is displayed. This
option is intended to ensure clean builds.

### CODE REVIEW

**Comment by nderjung** [comment]
This is about to break many builds ;)

**Comment by skuenzer** [comment]
Yes, if you enable it, it does break some builds. However, as default the option is off so we don't get any issues if we integrate this patch now. The idea is that the CI/CD system sets the option as part of the patch tests - of course after someone provided clean-up patches to make our base compile without warnings - which we anyways should always aim.

**Review by nderjung — CHANGES_REQUESTED** [review]
Hey thanks for this, can you please rebase?

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Review by nderjung — APPROVED** [review]
Reviewed-by: Alexander Jung <alex@unikraft.org>

**Pull request closed without merging**
