### PR TITLE
lib/uktest: Fixes layout of assert table on ARM64

### LINKED ISSUE #393: uk_test: self-tests fail on kvm / arm64
### Describe the bug

self-tests fail on kvm / arm64 due to an assertion. The assertion is triggered in `_uk_test_do_assert()`, and is caused by  `_uk_test_find_assert()` failing to find an assertion by line number.

### Steps to reproduce

Can reproduce with app-helloworld. Run menuconfig and apply the following changes:
* arch: Armv8
* plat: KVM
* uk_test: enable
 
Using gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf.

### Expected behavior

_No response_

### Which architectures were you using or does this bug affect?

_No response_

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
app-helloworld$ qemu-system-aarch64 -machine virt -cpu max -monitor none -serial stdio -kernel build/app-helloworld_kvm-arm64
test: uktest_myself_testsuite->uktest_test_sanity
    :	expected `((void *) 0)` to be 0 and was 0 ....................................... [ PASSED ]
[    0.000000] CRIT: [libuktest] <myself.c @  653> Assertion failure: assert
```

### PR DESCRIPTION
**Pull request by marcrittinghaus**
### Prerequisite checklist

 - [X] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [X] Tested your changes against relevant architectures and platforms;
 - [X] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [X] Updated relevant documentation.

### Base target

 - Architecture(s): [`arm64`]
 - Platform(s): [`kvm`]
 - Application(s): [N/A]

### Additional configuration

- `CONFIG_LIBUKTEST=y`
- `CONFIG_LIBUKTEST_ALL=y`

### Description of changes

This PR fixes the broken layout of the assertion table on ARM64 which causes the test code to not find the corresponding entry in the assertion table. The PR also fixes the page protections set on the table by the platform initialization code on ARM64 by moving it to a writeable memory area.

Closes #393

### CODE REVIEW

**Comment by craciunoiuc** [comment]
Hey @marcrittinghaus,

Isn't it a bit more suggestive to use `.hword` instead of `.dc.w`? (or even `.short`)[1]

Other than this, it looks good. I'll come back with the tag after I tested it.

[1] https://developer.arm.com/documentation/100067/0612/armclang-Integrated-Assembler/Data-definition-directives

**Comment by marcrittinghaus** [comment]
Hi @craciunoiuc,

`.short` maybe unsafe as it can be treated the same as `.word`. But I can change it to `.hword` if you prefer. Let me quickly push an update.

**Comment by craciunoiuc** [comment]
All good now 😉 

@michpappas approve it when you can

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
All good now 😉 

@michpappas please approve it when you can

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Comment by marcrittinghaus** [comment]
Thanks @craciunoiuc!

I forgot to update the commit message. It is fixed now, too.

**Comment by michpappas** [comment]
@marcrittinghaus many thanks for the fix! 🚀 

Approved-by: Michalis Pappas <mpappas@fastmail.fm>

**Review by michpappas — APPROVED** [review]
@marcrittinghaus, thanks for the fix! 🚀 

Approved-by: Michalis Pappas <mpappas@fastmail.fm>

**Pull request closed without merging**
