### PR TITLE
build: Use ISO 8601 format for `$(HOSTUTC)`

### LINKED ISSUE #1129: `lib/uklibid`: Building with GCC <= 11 for AArch64 results in error
### Describe the bug

Building with GCC <= 12 for AArch64 results in an error caused by the `uklibid` library, introduced in PR #1117. This is caused by the `lib/uklibid/libinfo.S` file, namely [line `39`](https://github.com/unikraft/unikraft/blob/staging/lib/uklibid/libinfo.S#L39).

### Steps to reproduce

Use the commands below to reproduce the issue:

```console
git clone https://github.com/unikraft/app-helloworld helloworld
cd helloworld/
./scripts/setup.sh
wget https://raw.githubusercontent.com/unikraft/app-testing/staging/scripts/generate.py -O scripts/generate.py
chmod a+x scripts/generate.py
./scripts/generate.py
./scripts/build/make-qemu-arm64.sh
```

### Expected behavior

The Redis build should work on AArch64.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
AS      libukdebug: libinfo.libuklibid.o
/home/razvan/projects/unikraft/maintainer-tools/workdir/apps/helloworld/workdir/unikraft/lib/uklibid/libinfo.S:39:44: error: macro "__STRINGIFY" passed 2 arguments, but takes just 1
   39 |                .asciz STRINGIFY(UK_UTCDATE))
      |                                            ^
In file included from /home/razvan/projects/unikraft/maintainer-tools/workdir/apps/helloworld/workdir/unikraft/lib/uklibid/include/uk/libid/info.h:10,
                 from /home/razvan/projects/unikraft/maintainer-tools/workdir/apps/helloworld/workdir/unikraft/lib/uklibid/libinfo.S:7:
/home/razvan/projects/unikraft/maintainer-tools/workdir/apps/helloworld/workdir/unikraft/include/uk/essentials.h:168: note: macro "__STRINGIFY" defined here
  168 | #define __STRINGIFY(x) #x
```

### PR DESCRIPTION
**Pull request by skuenzer**
### Description of changes

This PR makes the time format consistent for all host localizations and systems with the ISO 8601 format for UTC.

### CODE REVIEW

**Review by craciunoiuc — APPROVED** [review]
Tried it and it works. The change makes sense as discussed offline (previously it would fail based on the Locale).

One, minor, thing I noticed is that there is a trailing space on the output, not sure if caused by the new command:
```
[...] -D__GLOBALINFO__ -DUK_UTCDATE="2023-10-12T09:06:28+00:00 "  -g3 [...]
                                                              ^
```

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by skuenzer** [comment]
> Tried it and it works. The change makes sense as discussed offline (previously it would fail based on the Locale).
> 
> One, minor, thing I noticed is that there is a trailing space on the output, not sure if caused by the new command:
> 
> ```
> [...] -D__GLOBALINFO__ -DUK_UTCDATE="2023-10-12T09:06:28+00:00 "  -g3 [...]
>                                                               ^
> ```
> 
> Reviewed-by: Cezar Craciunoiu [cezar.craciunoiu@unikraft.io](mailto:cezar.craciunoiu@unikraft.io)

I found a fix for this: I had to move the comment away from the line where the timestamp is retrieved. Thanks for observing and reporting! :+1:

**Review by rares-miculescu — APPROVED** [review]
It works. Thanks, @skuenzer!

Reviewed-by: Rares Miculescu [miculescur@gmail.com](mailto:miculescur@gmail.com)

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
