### PR TITLE
build: Implement a more robust compiler detection

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

Instead of checking the compiler executable name, inspect the compiler's version output. This also works when there are symlinks involved or the executable name has additional text such as version numbers.

### CODE REVIEW

**Comment by vladandrew** [comment]
Hi Marco,

Just tested this and it works great. I was wondering, in what case would that sed be useful?

**Comment by jschlumpp** [comment]
Hey,
`sed` is used to extract the first word, which is the compiler name. So in the case of `gcc --version`:
```
gcc (GCC) 12.2.1 20230201
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
It would retrieve `gcc` and store it in the variable.

**Comment by vladandrew** [comment]
Hmm, on my side it doesn't seem to match correctly:

```bash
❯ gcc --version | head -n1 | sed 's/\s.*$$//'
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
```

I think there is an extra `$` at the end:

```bash
❯ gcc --version | head -n1 | sed 's/\s.*$//'
gcc
```

**Comment by jschlumpp** [comment]
The double dollar sign is necessary because you need to escape dollar signs in the Makefile. So in the actually executed `sed` command there is only one dollar sign left.

**Review by mariasfiraiala — COMMENTED** [review]
Thanks @mschlumpp! I've tested this on `x86` and it works fine with `gcc` and `clang`, however, on `AArch64` with both `aarch64-linux-gnu-gcc` and `gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu` the build fails with

```console
/home/maria/freestanding/unikraft/arch/arm/arm64/Makefile.uk:93: *** Require GCC version >= 4.9 found 11.2.  Stop.
```

**Comment by jschlumpp** [comment]
@mariasfiraiala I pushed an update, can you check whether the error still occurs?

**Review by mariasfiraiala — APPROVED** [review]
It's working fine now, thanks @mschlumpp.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Comment by vladandrew** [comment]
All good!

Reviewed-by: Vlad-Andrei Badoiu <vlad_andrei.badoiu@upb.ro>

**Review by vladandrew — APPROVED** [review]
All good!

Reviewed-by: Vlad-Andrei Badoiu <vlad_andrei.badoiu@upb.ro>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request closed without merging**
