### PR TITLE
scripts: Reimplement mkbootinfo.py with pyelftools

### PR DESCRIPTION
**Pull request by dinhngtu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): x86-64, amd64
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

The current `mkbootinfo.py` does not work with files having more than 100 sections (e.g. with C++, where lots of `.gcc_except_table*` sections are created), leading to an error of ".uk_bootinfo section not found".

This PR replaces `mkbootinfo.py` with an implementation that parses the unikernel binary with `pyelftools` then writes the resulting bootinfo structure with `struct`, therefore simplifying the bootinfo generation code.

Tested on x86-64 with both `CONFIG_UKPLAT_MEMRNAME=y` and `CONFIG_UKPLAT_MEMRNAME=n`.

### CODE REVIEW

**Comment by marcrittinghaus** [comment]
Hey @dinhngtu,

thanks for providing the version using the elftools. I thought about that, too. However, I decided against it, because this requires to install a python module as a prerequisite to be able to build Unikraft. I think this is suboptimal.

image

But to be fair here, I did not experience the problem with the output getting cut after 100 sections and this is suboptimal, too 😏

We plan to rewrite this in rust, eh, C to use `elf.h` also to remove the dependency on python. I am checking this out later this morning.

**Comment by dragosp27** [comment]
Hello @dinhngtu! I am trying to run this script for the Unikraft kernel built on KVM x86 but I get this error:
`Traceback (most recent call last):
  File "./support/scripts/mkbootinfo.py", line 124, in <module>
    main()
  File "./support/scripts/mkbootinfo.py", line 88, in main
    raise Exception("Segment base address 0x{:x} is not page-aligned".format(pbase))
Exception: Segment base address 0x11f060 is not page-aligned`
The previous version of the script runs fine for the same kernel. Do I need to do something else for this new version to run?

**Comment by dinhngtu** [comment]
> Hello @dinhngtu! I am trying to run this script for the Unikraft kernel built on KVM x86 but I get this error: `Traceback (most recent call last): File "./support/scripts/mkbootinfo.py", line 124, in <module> main() File "./support/scripts/mkbootinfo.py", line 88, in main raise Exception("Segment base address 0x{:x} is not page-aligned".format(pbase)) Exception: Segment base address 0x11f060 is not page-aligned` The previous version of the script runs fine for the same kernel. Do I need to do something else for this new version to run?

Hi, the memory layout of Unikraft's binary changed which broke the mkbootinfo script. Try cherrypicking this instead: https://github.com/dinhngtu/unikraft/commit/4cc3bc21e8aef4ce86b0dcbcffd9ce3fdf52147e

**Comment by razvand** [comment]
@mschlumpp , @marcrittinghaus , should we close this pull request?

**Comment by razvand** [comment]
I'm closing this PR based on the comments from @marcrittinghaus and @mschlumpp

**Pull request closed without merging**
