### PR TITLE
Add wrapper for ukrust-sys

### PR DESCRIPTION
**Pull request by TrueDoctor**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### CODE REVIEW

**Comment by cffs** [comment]
What prevent this to be in external `ukrust-sys` only? Why does it have to be in core?

**Comment by TrueDoctor** [comment]
> What prevent this to be in external `ukrust-sys` only? Why does it have to be in core?

I don't think it has to be a core lib, should I put it in a different repo then?

**Comment by vladandrew** [comment]
> > What prevent this to be in external `ukrust-sys` only? Why does it have to be in core?
> 
> I don't think it has to be a core lib, should I put it in a different repo then?

I was thinking of using the same lib-rust external repo. What do you think?

**Comment by cffs** [comment]
> I was thinking of using the same lib-rust external repo. What do you think?

Seems sensible to me. We could have a single `lib-rust` external repository with:
- the `Makefile.rules` for handling `.rs` and `Cargo.toml` files (see #291);
- the `ukrust-sys` crate (see #292);
- this wrapper crate.

**Comment by TrueDoctor** [comment]
Closing in favor of https://github.com/unikraft/lib-rust/pull/3

**Pull request closed without merging**
