### PR TITLE
lib/syscall_shim: Force argument order also for uk_vsyscall_r

### PR DESCRIPTION
**Pull request by marcrittinghaus**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

Commit 9acbeacedc91 forces the evaluation order of the arguments in `uk_vsyscall`. This commit applies the exact same fix to `uk_vsyscall_r`.

### CODE REVIEW

**Review by craciunoiuc — APPROVED** [review]
All good!

**Review by razvanvirtan — APPROVED** [review]
Looks good on my side.

Reviewed-by: Răzvan Vîrtan <virtanrazvan@gmail.com>

**Comment by marcrittinghaus** [comment]
@razvand I assigned you, because I think Alex should focus on his thesis and only be bothered to fix CI/CD if necessary 😃

I guess this is ready for approval. Thanks @craciunoiuc @razvanvirtan 🚀

**Review by razvand — APPROVED** [review]
Everything is OK. Thanks, @marcrittinghaus .

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Review by craciunoiuc — APPROVED** [review]
All good on my side!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Pull request closed without merging**
