### PR TITLE
  lib/uknetdev: Fix typo in `uk_netdev_tx_one` documentation

### PR DESCRIPTION
**Pull request by haesbaert**
We now know RX was written first :).

### Prerequisite checklist

 - [X] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [X] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

Just a typo in the function api

### CODE REVIEW

**Comment by nderjung** [comment]
Hi @haesbaert! Thanks for the fix! To get this upstream, please can you reword your commit to match the adjusted title of the PR and include a [DCO Sign-off](https://unikraft.org/docs/contributing/submitting-changes/)? Thanks!

_Edit:_ Please can you remove the message body. Thanks! (Also sorry )-: )

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by nderjung** [comment]
Hi @haesbaert, just need to remove the Git commit message body before I can approve this (or, preferably, indicate specifically why the switch occurred in a bit more detail). Thanks!

**Comment by craciunoiuc** [comment]
@nderjung 👀

**Review by nderjung — APPROVED** [review]
All good! Thanks :)

Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request closed without merging**
