### PR TITLE
plat/kvm: Enable VGA by default on QEMU x86_64

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`x86_64`]
 - Platform(s): [`kvm`]
 - Application(s): [N/A]

### Description of changes

Enable VGA by default on QEMU x86_64. This was removed during the migration of VGA to drivers.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by mogasergiu** [comment]
Why do we enable VGA by default? :thinking: 
It does not work properly with color codes and it is also super slow and crashes with SMP. Would it be better to just keep the COMs only?

**Review by mogasergiu — APPROVED** [review]
Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Comment by michpappas** [comment]
> Why do we enable VGA by default? 🤔 It does not work properly with color codes and it is also super slow and crashes with SMP. Would it be better to just keep the COMs only?

This is ultimately on @simon, but just FTR, it's not that we enable it now. This PR restores the default which is VGA on, which was unintentionally disabled in #1464.

**Comment by skuenzer** [comment]
> > Why do we enable VGA by default? 🤔 It does not work properly with color codes and it is also super slow and crashes with SMP. Would it be better to just keep the COMs only?
> 
> This is ultimately on @simon, but just FTR, it's not that we enable it now. This PR restores the default which is VGA on, which was unintentionally disabled in #1464.

This is a good point. To keep the previous behavior (before #1464), I would keep it on for now as well. This is for ease of getting started, especially for people running the QEMU image on environments like `libvirt`.
However, I agree, adding VGA is against our "as minimal as possible" principle. I am thinking we can fix this with completing re-arch of platforms and maybe introduce 2 different QEMU/x86 targets, one without having a VGA.

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request merged**
