### PR TITLE
drivers/ukconsole/vga: Add initial sanity check

### PR DESCRIPTION
**Pull request by florommel**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `kvm`, `xen`
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBUKCONSOLE_VGA=y`

### Description of changes

When the VGA driver is enabled in firecracker builds, the kernel fails the following assertion during boot:
```
<memory.c @  374> Assertion failure: ml->flags == mr->flags
```
caused by the illicitly registered memory region for the (in this case, non-existing) VGA controller.

This PR adds an initial sanity check for the VGA controller that should detect a non-existing VGA controller and also an unexpectedly configured VGA controller.

I have tested this with firecracker (no VGA) and QEMU (with VGA), but not yet with XEN.

An alternative to this PR would be to statically disallow VGA for firecracker builds.

### CODE REVIEW

**Comment by skuenzer** [comment]
Thanks for this PR! This is a great addition to the VGA driver. We are undergoing a re-architecture of the architecture, platform and driver code. Some things aren't finished yet, but the goal is that VGA should not be available for firecracker, Xen, and any arch, platform that doesn't support it at all. However, your patch makes still a lot of sense to add, considering the flexibility you have with QEMU.

**Comment by florommel** [comment]
Okay, that seems reasonable.

I checked the relevant QEMU (v.9.1.1) options (`-vga none`, `-nodefaults`). It seems that QEMU provides the basic VGA controller functionality (including the memory region) even when VGA is disabled.
Nevertheless, I think the proposed sanity check is valuable. There may be QEMU configurations that I haven't tested (and it may also prove useful in other virtualization environments supported in the future).

**Review by skuenzer — APPROVED** [review]
Thanks a lot @florommel, the PR looks great, we will take it in.

Reviewed-by: Simon Kuenzer <simon@unikraft.io>
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Comment by michpappas** [comment]
Hi @florommel, merging this failed with conflicts, could you rebase?

**Comment by razvand** [comment]
@michpappas , this is now rebased. Merge at your earliest convenience.

**Pull request merged**
