### PR TITLE
Various fixes for application compatibility

### PR DESCRIPTION
**Pull request by marcrittinghaus**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

This PR includes fixes for various bugs and missing features discovered when working on application compatibility. See the individual commits for more information.

### CODE REVIEW

**Comment by John-Ted** [comment]
https://github.com/unikraft/unikraft/pull/834/commits/109f494e55ecb59aaf9517074cf3047d3161cff2
The [`helloworld` Go static app](https://github.com/unikraft/static-pie-apps/tree/master/lang/go) still does not work for me, it does not output anything. Should it work, or are there any special options I need to enable in the config?

Everything else looks good.

**Comment by marcrittinghaus** [comment]
> [109f494](https://github.com/unikraft/unikraft/commit/109f494e55ecb59aaf9517074cf3047d3161cff2) The [`helloworld` Go static app](https://github.com/unikraft/static-pie-apps/tree/master/lang/go) still does not work for me, it does not output anything. Should it work, or are there any special options I need to enable in the config?
> 
> Everything else looks good.

Hi @John-Ted,

then probably it is a configuration issue. Here is my [.config.zip](https://github.com/unikraft/unikraft/files/11260745/default.config.zip) file.

**Comment by John-Ted** [comment]
Still does not work, here the output I get (no hello world message):
```
SeaBIOS (version 1.13.0-1ubuntu1.1)


iPXE (http://ipxe.org) 00:02.0 C100 PCI2.10 PnP PMM+7FF8C800+7FECC800 C100
                                                                               


Booting from ROM...
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
             Epimetheus 0.12.0~a827e2ac
arch_prctl(0x3001, 0x47f45fda0, ...) = Invalid argument (-22)
brk(NULL) = va:0x400200000
brk(va:0x4002011c0) = va:0x4002011c0
arch_prctl(0x1002, 0x400200880, ...) = 0
uname(0x47f45fb80, 0x400200880, ...) = 0
set_tid_address(0x400200b50, 0x47f45fc03, ...) = 0
set_robust_list(0x400200b60, 0x18, ...) = Function not implemented (-38)
rt_sigaction(0x20, 0x47f45fb00, ...) = 0
rt_sigaction(0x21, 0x47f45fb00, ...) = 0
rt_sigprocmask(0x1, 0x47f45fc78, ...) = 0
prlimit64(0x0, 0x3, ...) = 0
readlink("/proc/self/exe", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"..., 4096) = No such file or directory (-2)
brk(va:0x4002221c0) = va:0x4002221c0
brk(va:0x400223000) = va:0x400223000
mprotect(va:0x47f204000, 786432, PROT_READ) = OK
sched_getaffinity(0x0, 0x2000, ...) = Function not implemented (-38)
openat(AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/hpage_pmd_size", O_RDONLY) = No such file or directory (-2)
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0x1000008000
mmap(va:0xc000000000, 67108864, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0xc000000000
mmap(va:0xc000000000, 67108864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, fd:-1, 0) = va:0xc000000000
mmap(NULL, 33554432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0x1000048000
mmap(NULL, 2164736, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0x1002048000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0x1002259000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, fd:-1, 0) = va:0x1002269000
Console terminated, terminating guest (PID: 90246)...
```

**Comment by marcrittinghaus** [comment]
Ok, interesting. I rebuilt the GO app and that works. But indeed, if you try the version that is part of the static APPs repo, I have the same issue.

**Review by John-Ted — APPROVED** [review]
Reviewed-by: Ioan-Teodor Teugea <teodor.teugea@gmail.com>

**Comment by John-Ted** [comment]
> Ok, interesting. I rebuilt the GO app and that works. But indeed, if you try the version that is part of the static APPs repo, I have the same issue.

I tried rebuilding the app and it works, looks like there is an issue with that particular executable

**Comment by marcrittinghaus** [comment]
I traced the instruction flow up to the point where we crash. The problem with the GO app in the repo is that it is GO-1.13. The crash happens in a call to `runtime.nanotime()`. This is due to the VDSO not present on Unikraft. Although the call checks if there is a VDSO entry for `clockgettime` the fallback is to use `gettimeofday` from the VDSO (without check) [1]. On newer versions of GO, the fallback is to use the syscall [2].

[1] https://github.com/golang/go/blob/ed4f3f313438b8765da6c4605060529761db0797/src/runtime/sys_linux_amd64.s#L277
[2] https://github.com/golang/go/blob/ce10e9d84574112b224eae88dc4e0f43710808de/src/runtime/sys_linux_amd64.s#L283

**Review by csvancea — APPROVED** [review]
Reviewed-by: Cosmin Vancea csvancea@gmail.com

**Review by razvand — APPROVED** [review]
Thanks, @marcrittinghaus.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
