### PR TITLE
drivers/virtio: Fix interrupt flag check

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): `kvm`
 - Application(s): N/A

### Description of changes

The check used a bit-OR instead of a bit-AND to check whether the flag is set.

### CODE REVIEW

**Review by craciunoiuc — COMMENTED** [review]
Hey @mschlumpp @nderjung 

All good here right? Should we add the tags?

**Comment by marcrittinghaus** [comment]
> Hey @mschlumpp @nderjung
> 
> All good here right? Should we add the tags?

@craciunoiuc Yes, please add your tag 👍🏻

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by marcrittinghaus — APPROVED** [review]
In its simplicity beautiful like Mona Lisa 🎨

Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
