### PR TITLE
Fix Missing URL and Inquiry about Open Positions

### PR DESCRIPTION
**Pull request by yfenes**
### Change:
This PR includes a fix for a missing URL in the README. 

### Inquiry:
I am very interested in the goals and technology of Unikraft, that's why I proactively created this PR and would like to know if there are **any open positions** (ideally, B2B contract) or opportunities for more significant contributions. 

I am excited to bring my skills to the project and collaborate on advancing Unikraft's innovative platform.

Should there be suitable openings, please feel free to reach out to me at: yfenes@gmail.com.
Thank you for considering.

### CODE REVIEW

**Comment by razvand** [comment]
@yfenes , for open positions, it's best to use the [Discord server](https://unikraft.org/discord).

**Review by StefanJum — CHANGES_REQUESTED** [review]
Hi @yfenes. Can you use your full name and email in the commiter field? It's `Commit: GitHub <noreply@github.com>` now. Use `git config --global user.name` and `user.email` when commiting.

Also, please modify the commit message to follow the convention. Use something like `README.md:  Fix RISC-V url in the Features section`.

All good besides that.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
