### PR TITLE
lib/uktest: Make LIBUKTEST_TEST_MYSELF option enable/disable uktest's tests

### PR DESCRIPTION
**Pull request by flpostolache**
This commit disables the myself testsuite when LIBUKTEST_TEST_MYSELF is not selected.

Signed-off-by: Florin Postolache <florin.postolache80@gmail.com>

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### CODE REVIEW

**Review by marcrittinghaus — COMMENTED** [review]
Hi @maniatro111,

thanks for putting this together 😃 I tested it, and it works as expected. You could argue that the commit title is a bit unclear. Other than that, it is fine 👍🏻

**Comment by nderjung** [comment]
If it's ok by you @marcrittinghaus happy to approve.

**Comment by marcrittinghaus** [comment]
@nderjung Yes, thanks! Go ahead.

**Review by nderjung — APPROVED** [review]
Thanks @maniatro111!

Reviewed-by: Alexander Jung <alex@unikraft.io>
Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request closed without merging**
