### PR TITLE
plat/xen: Fix implicit int cast build error

### LINKED ISSUE #1512: `plat/xen`: Building with Clang fails on ARM64: `incompatible pointer to integer conversion assigning`
### Describe the bug

Building applications with Clang for Xen ARM64 results in a build error.

### Steps to reproduce

Build C Hello with Clang for Xen/ARM64 in the [`catalog-core` repository](https://github.com/unikraft/catalog-core). Follow the steps:

1. Clone the repository:

   ```console
   git clone https://github.com/unikraft/catalog-core
   ```

1. Enter the `c-hello/` directory:

   ```console
   cd catalog-core/c-hello/
   ```
   
1. Switch to the `scripts` branch:

   ```console
   git checkout scripts
   ```

1. Build C Hello for Xen/ARM64:

   ```console
   ./build.xen.arm64
   ```

   The build error occurs.

### Expected behavior

Build is successful, without errors.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

xen

### Relevant log output

```shell
/home/razvan/orgs/unikraft/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:176:14: error: incompatible pointer to integer conversion assigning to '__u64' (aka 'unsigned long') from 'char[
8]' [-Wint-conversion]                                                                                                                                                                        
  176 |         bi->cmdline = CONFIG_UK_NAME;                                                                                                                                                 
      |                     ^ ~~~~~~~~~~~~~~                                                                                                                                                  
/home/razvan/orgs/unikraft/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:184:16: error: incompatible pointer to integer conversion assigning to '__u64' (aka 'unsigned long') from 'const
 char *' [-Wint-conversion]                                                                                                                                                                   
  184 |                         bi->cmdline = fdtcmdline;
```

### PR DESCRIPTION
**Pull request by andreistan26**
Building xen on arm64 with Clang would fail due to an implicit cast from char * to __uptr.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `arm64`
 - Platform(s): `xen`
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

Builds on `xen/arm64` using `clang` would fail due to an implicit cast. This PR makes the cast explicit.

### CODE REVIEW

**Comment by oleksiimoisieiev** [comment]
LGTM 

Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by razvand** [comment]
@oleksiimoisieiev , please also add you approved button, so I can then merge this.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Comment by skuenzer** [comment]
Hey, sorry, if you don't mind, we would fix the problem with this commit: https://github.com/unikraft/unikraft/pull/1501/commits/7ee3f1ddf0bda5143a8bd46d95590c8678a97ea0
I faced the same issue with a more recent GCC version. However, I think we should not plain cast to `__u64`, rather take a type that is describing the pointer as integer (`__uptr`). This way we make sure that we still get a warning emitted if we change the boot structure with an incompatible target type or if for some weird reason the pointer type changes to something incompatible (e.g., different architecture).

**Comment by andreistan26** [comment]
Makes sense, thanks,  fixed it

**Comment by skuenzer** [comment]
> Makes sense, thanks, fixed it

Okay, I actually meant that this will get fixed with PR #1501, since the commit is included there. Your update is fine, we'll take it and I'll remove the fixing commit from my PR.

**Review by skuenzer — APPROVED** [review]
Reviewed-by: Simon Kuenzer <simon@unikraft.io>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request merged**
