### PR TITLE
lib/ukvmem: Compile all source files for ISR context

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBUKVMEM=y`

### Description of changes

The main and individual pagefault handlers are executed in an ISR context. Not marking the files as `isr`, will cause the usual trouble (clobbered vector registers).

### CODE REVIEW

**Review by RaduNichita — COMMENTED** [review]
All good from my side. One comment: for now this works only for kvm .

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Comment by adinasm** [comment]
Seems to be working fine for kvm.

Reviewed-by: Adina Smeu <adina.smeu@gmail.com>

**Review by adinasm — COMMENTED** [review]
Seems to be working fine for kvm.

Reviewed-by: Adina Smeu <adina.smeu@gmail.com>

**Review by marcrittinghaus — APPROVED** [review]
Thanks!

Reviewed-by: Radu Nichita <radunichita99@gmail.com>
Reviewed-by: Adina Smeu <adina.smeu@gmail.com>
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
