### PR TITLE
lib/posix-process: Fix build warnings

### LINKED ISSUE #818: `lib/posix-process`: Build warnings in `deprecated.c`
### Describe the bug

When building `lib/posix-process`, warnings are signaled for the `deprecated.c` function.

**Hackathon points**: 10

### Steps to reproduce

This happens with [`app-elfloader`](https://github.com/unikraft/app-elfloader), but any application using `lib/posix-process` should be able to get the warnings.

### Expected behavior

There shouldn't be any build warnings.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
CC      libposix_process: deprecated.o
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c: In function ‘tcgetpgrp’:
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c:242:21: warning: unused parameter ‘fd’ [-Wunused-parameter]
  242 | pid_t tcgetpgrp(int fd)       
      |                 ~~~~^~                 
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c: In function ‘nice’:
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c:250:14: warning: unused parameter ‘inc’ [-Wunused-parameter]
  250 | int nice(int inc)                    
      |          ~~~~^~~      
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c: In function ‘prlimit’:
/home/razvan/projects/unikraft/bin-compat/unikraft/lib/posix-process/deprecated.c:408:19: warning: unused parameter ‘pid’ [-Wunused-parameter]
  408 | int prlimit(pid_t pid, int resource, const struct rlimit *new_limit,
      |             ~~~~~~^~~
```

### PR DESCRIPTION
**Pull request by kouk**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [X] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

Fixed build warnings about unused arguments.

GitHub-Fixes: #818

### CODE REVIEW

**Review by razvand — CHANGES_REQUESTED** [review]
Hi, @kouk. Please use `lib/posix-process` as commit prefix, as in the [contributing guidelines](https://unikraft.org/docs/contributing/submitting-changes/#commits).

Remove the reference to the issue in the title and add:

```
GitHub-Fixes: #818
```

**Comment by kouk** [comment]
@razvand done

**Review by razvand — CHANGES_REQUESTED** [review]
@kouk, please use a proper name and e-mail as part of the commit message. Reset the author.

**Review by razvand — APPROVED** [review]
@kouk, this is OK with me. @StefanJum, you can do add your tag and then I'll approve this PR.

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
