### PR TITLE
Solved some compilation warnings

### LINKED ISSUE #242: Clean up warnings from core build
The current build is not "clean" and has some outstanding warnings, including:

```
/tmp/build/80754af9/built/unikraft/lib/nolibc/stdio.c: In function 'fputc':
/tmp/build/80754af9/built/unikraft/lib/nolibc/stdio.c:497:5: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
  497 |  if (ret == 1)
      |     ^
/tmp/build/80754af9/built/unikraft/lib/vfscore/mount.c: In function '__uk_syscall_r_sync':
/tmp/build/80754af9/built/unikraft/lib/vfscore/mount.c:380:1: warning: no return statement in function returning non-void [-Wreturn-type]
  380 | }
      | ^
/tmp/build/80754af9/built/unikraft/lib/vfscore/main.c: In function 'ioctl':
/tmp/build/80754af9/built/unikraft/lib/vfscore/main.c:686:41: warning: passing argument 3 of 'uk_syscall_e_ioctl' makes integer from pointer without a cast [-Wint-conversion]
  686 |  return uk_syscall_e_ioctl(fd, request, arg);
      |                                         ^~~
      |                                         |
      |                                         void *
In file included from /tmp/build/80754af9/built/unikraft/lib/vfscore/main.c:54:
/tmp/build/80754af9/built/unikraft/lib/vfscore/main.c:649:10: note: expected 'long int' but argument is of type 'void *'
  649 |   void*, arg)
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:108:41: note: in definition of macro 'UK_S_ARG_LONG'
  108 | #define UK_S_ARG_LONG(type, arg)   long arg
      |                                         ^~~
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:100:54: note: in expansion of macro 'UK_ARG_MAP1'
  100 | #define UK_ARG_MAP2(m, type, arg, ...) m(type, arg), UK_ARG_MAP1(m, __VA_ARGS__)
      |                                                      ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:101:54: note: in expansion of macro 'UK_ARG_MAP2'
  101 | #define UK_ARG_MAP3(m, type, arg, ...) m(type, arg), UK_ARG_MAP2(m, __VA_ARGS__)
      |                                                      ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/include/uk/essentials.h:158:29: note: in expansion of macro 'UK_ARG_MAP3'
  158 | #define __UK_CONCAT_X(a, b) a##b
      |                             ^
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:199:13: note: in expansion of macro 'UK_ARG_MAPx'
  199 |  long ename(UK_ARG_MAPx(x, UK_S_ARG_LONG, __VA_ARGS__))  \
      |             ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:219:37: note: in expansion of macro '__UK_LLSYSCALL_R_DEFINE'
  219 | #define _UK_LLSYSCALL_R_DEFINE(...) __UK_LLSYSCALL_R_DEFINE(__VA_ARGS__)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/lib/syscall_shim/include/uk/syscall.h:221:2: note: in expansion of macro '_UK_LLSYSCALL_R_DEFINE'
  221 |  _UK_LLSYSCALL_R_DEFINE(__UK_SYSCALL_DEF_NARGS(__VA_ARGS__), \
      |  ^~~~~~~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/lib/vfscore/main.c:648:1: note: in expansion of macro 'UK_LLSYSCALL_R_DEFINE'
  648 | UK_LLSYSCALL_R_DEFINE(int, ioctl, int, fd, unsigned long int, request,
      | ^~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by RaduMantu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64` 
 - Platform(s): `kvm`
 - Application(s): N/A

### Description of changes

Fixed 4 compilation warnings for core libraries:

- returning uninitialized value in `fputc()`
- missing return statement in `sync()`
- added cast to `unsigned long` for address in `ioctl()`
- replaced implicit declaration of `getpid()` when libc-style stubs are not generated

### CODE REVIEW

**Review by nderjung — CHANGES_REQUESTED** [review]
Hi @RaduMantu! Thanks for the PR and great work again at [USoC21](https://usoc21.unikraft.org)!

To get this PR ready to be merged, please can you adjust each commit message so that it:

 1. each commit has a short title, starting with the library prefix, e.g. `lib/vfscore: `;
 2. that the line-length of each commit message is no longer than 75 chars;
 3. put the full description within the commit message after the title.

Thanks!

**Comment by RaduMantu** [comment]
Hi @nderjung,

Sorry for the long delay in dealing with these issues.
I've addressed the problems that you pointed out. My fault for not using **checkpatch.pl** beforehand.

I'll take a look over the other pending PR tomorrow at the latest.

Thanks for taking the time!

**Comment by craciunoiuc** [comment]
Hey @RaduMantu,

All things look good. I was able to reproduce the warnings and fix them with your commits.

The only problem is that the second dcb5db6026273359fcc1a7804aa3842ddc51eea6 and the third 358e27d02c1c5fe31d44dd88dae9f3d5da46a7fd commit were fixed in the meantime by @skuenzer in the same fashion.
As such, there is a merge conflict. Simply removing the second and third conflict should fix the problem.
After you do this, I will add the tag and it will get merged.

Sorry your patches weren't accepted sooner. I think people just got caught up with other stuff 🙁

Cezar

**Review by craciunoiuc — CHANGES_REQUESTED** [review]
Hey @RaduMantu,

All things look good. I was able to reproduce the warnings and fix them with your commits.

The only problem is that the second dcb5db6026273359fcc1a7804aa3842ddc51eea6 and the third 358e27d02c1c5fe31d44dd88dae9f3d5da46a7fd commit were fixed in the meantime by @skuenzer in the same fashion.
As such, there is a merge conflict. Simply removing the second and third conflict should fix the problem.
After you do this, I will add the tag and it will get merged.

Sorry your patches weren't accepted sooner. I think people just got caught up with other stuff 🙁

Cezar

**Comment by RaduMantu** [comment]
Hi @craciunoiuc ,

Thanks for the feedback.

> Simply removing the second and third conflict should fix the problem.

I removed them both. Should not be any more conflicts.

> Sorry your patches weren't accepted sooner. I think people just got caught up with other stuff slightly_frowning_face

It's ok. These are pretty small changes and I get they aren't a priority. Also, I could have responded quicker to change requests :/

I also looked over your comments on the other PR and will address them first thing tomorrow morning.

**Comment by craciunoiuc** [comment]
Hey @RaduMantu,

All good now!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
Hey @RaduMantu,

All good now!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
All good now!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

**Review by nderjung — APPROVED** [review]
Thanks! 🐒 

Approved-by: Alexander Jung <a.jung@lancs.ac.uk>

**Pull request closed without merging**
