### PR TITLE
drivers/virtio: Replace libc types with unikraft defined

### PR DESCRIPTION
**Pull request by rares-miculescu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

Some files inside Unikraft use libc data types. This PR changes those data types with Unikraft-specific data types, inside drivers/virtio.

### CODE REVIEW

**Review by RaduNichita — COMMENTED** [review]
I have a question:

* Is there a equivalent type for `unsigned long` for [drivers/virtio/pci/virtio_pci.c](https://github.com/unikraft/unikraft/pull/1345/commits/db8a2c155d203661961a03cd99f293e85379a94d#diff-194bf4ef837971a22c2ac807ffb31eab0e01a246169e107ceeeba75632cd3c6f) - line 137

* For drivers/virtio/net/virtio_net.c:192 is there an equivalent for `unsigned`? 

Also, please fix the commit message, as mentioned in https://github.com/unikraft/unikraft/pull/1343

**Comment by rares-miculescu** [comment]
@RaduNichita, in this PR, I focused on replacing `stdint.h` types with Unikraft defined, but I dug up the origin of the variables and I came up with the conclusion that the `unsigned long` and `unsigned` can be replaced with `__u64` and `__u8`. I will change this as well.

**Review by mariasfiraiala — APPROVED** [review]
Looks good to me, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by RaduNichita — APPROVED** [review]
All good, thanks @rares-miculescu 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Comment by michpappas** [comment]
> @RaduNichita, in this PR, I focused on replacing `stdint.h` types with Unikraft defined, but I dug up the origin of the variables and I came up with the conclusion that the `unsigned long` and `unsigned` can be replaced with `__u64` and `__u8`. I will change this as well.

In principle, I would agree with @rares-miculescu here, the scope of this work is to replace libc types. On the specific changes:

`get_promiscuous` is the implementation of the netdev op defined in `netdev_core.h` which returns `unsigned`: https://github.com/unikraft/unikraft/blob/staging/lib/uknetdev/include/uk/netdev_core.h#L349. Therefore, the original definition was correct. In fact, the updated version generates a warning:
```
/home/mpp/devel/unikraft/uk_helloworld/unikraft/drivers/virtio/net/virtio_net.c:1258:28: warning: initialization of ‘unsigned int (*)(struct uk_netdev *)’ from incompatible pointer type ‘__u8 (*)(struct uk_netdev *)’ {aka ‘unsigned char (*)(struct uk_netdev *)’} [-Wincompatible-pointer-types]
 1258 |         .promiscuous_get = virtio_net_promisc_get,
      |                            ^~~~~~~~~~~~~~~~~~~~~~
/home/mpp/devel/unikraft/uk_helloworld/unikraft/drivers/virtio/net/virtio_net.c:1258:28: note: (near initialization for ‘virtio_netdev_ops.promiscuous_get’)
```
Please revert this change.

Regarding the cast in `virtio_pci_handle()`: `pci_isr_addr` is already of type `__u64` so the cast in redundant. I don't understand the purpose of the double cast (i.e. `virtio_cread8((void *)(unsigned long)d->pci_isr_addr, 0)`) before this change was applied, as casting `_u64` to `void *` would already suffice. So you can either remove the second cast, or leave it as it was.

**Review by michpappas — CHANGES_REQUESTED** [review]
> @RaduNichita, in this PR, I focused on replacing `stdint.h` types with Unikraft defined, but I dug up the origin of the variables and I came up with the conclusion that the `unsigned long` and `unsigned` can be replaced with `__u64` and `__u8`. I will change this as well.

In principle, I would agree with @rares-miculescu here, the scope of this work is to replace libc types. On the specific changes:

`get_promiscuous` is the implementation of the netdev op defined in `netdev_core.h` which returns `unsigned`: https://github.com/unikraft/unikraft/blob/staging/lib/uknetdev/include/uk/netdev_core.h#L349. Therefore, the original definition was correct. In fact, the updated version generates a warning:
```
/home/mpp/devel/unikraft/uk_helloworld/unikraft/drivers/virtio/net/virtio_net.c:1258:28: warning: initialization of ‘unsigned int (*)(struct uk_netdev *)’ from incompatible pointer type ‘__u8 (*)(struct uk_netdev *)’ {aka ‘unsigned char (*)(struct uk_netdev *)’} [-Wincompatible-pointer-types]
 1258 |         .promiscuous_get = virtio_net_promisc_get,
      |                            ^~~~~~~~~~~~~~~~~~~~~~
/home/mpp/devel/unikraft/uk_helloworld/unikraft/drivers/virtio/net/virtio_net.c:1258:28: note: (near initialization for ‘virtio_netdev_ops.promiscuous_get’)
```
Please revert this change.

Regarding the cast in `virtio_pci_handle()`: `pci_isr_addr` is already of type `__u64` so the cast in redundant. I don't understand the purpose of the double cast (i.e. `virtio_cread8((void *)(unsigned long)d->pci_isr_addr, 0)`) before this change was applied, as casting `_u64` to `void *` would already suffice. So you can either remove the second cast, or leave it as it was.

**Comment by michpappas** [comment]
Please notice that https://github.com/unikraft/unikraft/pull/1343#pullrequestreview-1942305875 applies here too.

**Review by michpappas — APPROVED** [review]
Reviewed-by: Michalis Pappas <michalis@unikraft.io>
Approved-by: Michalis Pappas <michalis@unikraft.io>

**Pull request merged**
