### PR TITLE
arch/: Replace libc types with Unikraft defined

### PR DESCRIPTION
**Pull request by rares-miculescu**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes

Replace libc data types with Unikraft defined, to make `arch/` independent of libc

### CODE REVIEW

**Comment by andreistan26** [comment]
I don't get how the `uk/arch/types.h` header is included in the target file.
 Is it passed to a compiler command option like `-include` ?

**Comment by rares-miculescu** [comment]
@andreistan26, when testing, I noticed that it did not fail, so I assumed it is included through other files.

**Review by mariapana — APPROVED** [review]
Handy change along #1368! Looks good.

Reviewed-by: Maria Pana <maria.pana4@gmail.com>

**Review by andreistan26 — APPROVED** [review]
All good on my side.

Reviewed-by: Andrei Stan [andreistan2003@gmail.com](mailto:andreistan2003@gmail.com)

**Comment by michpappas** [comment]
> @andreistan26, when testing, I noticed that it did not fail, so I assumed it is included through other files.

@rares-miculescu that's the case indeed, but it shouldn't be that way. Every header must explicitly include its dependencies. You need to add `#include <uk/arch/types.h>`. Other than that it looks good, so once you apply this change I'll merge.

**Review by michpappas — APPROVED** [review]
Thanks!

Approved-by: Michalis Pappas <michalis@unikraft.io>

**Pull request merged**
