### PR TITLE
Add unikraft rust binding generation

### PR DESCRIPTION
**Pull request by TrueDoctor**
### Prerequisite checklist

 - [ x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### CODE REVIEW

**Comment by vladandrew** [comment]
Hi Denis,

Would it make sense to add this to the external lib-rust repo? And maybe, we could progressively integrate more and more from that repo into the main repo?

**Comment by cffs** [comment]
I have the same question: what prevent generating those bindings from an external library?
Additionally, if we use `lib-rust` both for Makefile rules allowing to use cargo for user-space apps (see #291), and for bindings to unikraft core, then need to put it behind an option. One might want to use cargo integration `without` the bindings.

**Comment by cffs** [comment]
Assuming we put this in core, what would be the relation between `lib/ukrust` (see #293) and `lib/ukrust-sys`? Shouldn't those be merged?

**Comment by TrueDoctor** [comment]
@vladandrew @cffs 
Yes, this can be an external repo, it is not even integrated as an internal library, rather just a crate that you can depend on.
The one tricky thing is that It depends on the list of header files being exposed by the buildsystem, so it is not completely self sustained. We might be able to factor out the required changes to `Makefile.rules` into this repo.
We would not need to put the binding generation behind options because it is not actually executed by the build system directly but rather by the dependencies.
ukrust-sys provides raw bindings while ukrust will be an opinionated easier to use wrapper.
they don't have to live in separate repos, but it is rust convention (and quite sensible I think) to split that into two crates.

**Comment by TrueDoctor** [comment]
https://github.com/unikraft/lib-rust/pull/2

**Pull request closed without merging**
