### PR TITLE
Fix spinlock headers

### PR DESCRIPTION
**Pull request by marcrittinghaus**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [`arm64` and generic]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

This PR adds some missing includes and checks to the spinlock headers as well as fixing spelling mistakes.
Thanks @Sairajkodilkar for pointing out the missing `essentials.h`! 😃

### CODE REVIEW

**Comment by razvanvirtan** [comment]
All good on my side.

Reviewed-by:  <your@email.com>

**Review by razvanvirtan — APPROVED** [review]
All good on my side.

Reviewed-by:  Răzvan Vîrtan <virtanrazvan@gmail.com>

**Comment by marcrittinghaus** [comment]
@michpappas Also here. Could you have a quick look and approve if everything is fine from your side?

**Comment by michpappas** [comment]
Approved-by: Michalis Pappas <mpappas@fastmail.fm>

**Pull request closed without merging**
