### PR TITLE
lib/uksignal: Solve redefining conflicts

### PR DESCRIPTION
**Pull request by dragosargint**
There are many functions that are defined in musl as well as in uksignal.
When using musl we want to use the musl functions. When we use musl the
`LIBSYSCALL_SHIM_NOWRAPPER` macro is set, which leads to the setting of
`UK_LIBC_SYSCALLS` to 0. We can use this to exclude the redefined functions
from vfscore.

This PR is part of a series:
https://github.com/unikraft/unikraft/pull/454
https://github.com/unikraft/unikraft/pull/453
https://github.com/unikraft/unikraft/pull/442
https://github.com/unikraft/unikraft/pull/441

Signed-off-by: Dragos Iulian Argint <dragosargint21@gmail.com>

### CODE REVIEW

**Comment by craciunoiuc** [comment]
I did an initial pass over it and all's good.

**Review by mogasergiu — APPROVED** [review]
Looks good to me.

Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

**Review by mogasergiu — APPROVED** [review]
Looks good to me.

Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

**Pull request closed without merging**
