### PR TITLE
plat/xen/x86_64: Add missing segment alignment for `xen`

### PR DESCRIPTION
**Pull request by andreistan26**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `xen`
 - Application(s): N/A

### Description of changes

Make the second segment in a `xen/x86-64` ELF aligned to the page size.
This fixes a memory overlap issue that triggers an assert during
memory coalescing.

### CODE REVIEW

**Comment by PAN740623** [comment]
错误报告 阻止

**Review by mogasergiu — CHANGES_REQUESTED** [review]
Hi, thanks for looking into this! Looks good! Just a couple of things :nerd_face::
- s/alignement/alignment/
- s/This fixes a memory overlap/This fixes a memory region overlap
- no "Merge" commits! You probably got this from an attempt to rebase :smiley:. In the future you can simply `git remote update; git pull origin staging --rebase`. Now you will have to force push the branch your PR is based on :point_up: .

**Review by mogasergiu — APPROVED** [review]
Thanks for your work.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>
Approved-by: Sergiu Moga <sergiu@unikraft.io>

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
