### PR TITLE
lib/posix-fdio: Add bincompat support for RWF_*

### PR DESCRIPTION
**Pull request by andreittr**
### Description of changes

This change adds values for RWF_* flags in posix-fdio, allowing it to interpret their meaning even without support from our (no)libc. This enhances binary compatibility.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Additional configuration

N/A

### CODE REVIEW

**Review by Mihnea0Firoiu — APPROVED** [review]
All good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

**Comment by robertZamfir601** [comment]
Hello! The PR looks good, the functions are a lot clearer this way. I have two questions/observations though: 

1. For `RWF_NOWAIT`, previously the flag was ignored, but the user could still read. Now we will return an error that might break some apps that worked previously. Could this be a problem?
2. Should we use `uk_pr_warn_once` for `RWF_SYNC`, `RWF_DYNC`  and `RWF_APPEND` also? 

Everything else looks good.

**Comment by andreittr** [comment]
Hi @robertZamfir601 , thanks for your review!
> For RWF_NOWAIT, previously the flag was ignored, but the user could still read. Now we will return an error that might break some apps that worked previously. Could this be a problem?

This is a good point. While at first it might seem more compatible to ingore the flag and move ahead with potentially blocking I/O, that poses issues for workloads that rely on the documented semantics of that flag.
The program woud run, yes, but it may not work as expected, and without a clear sign of why or that it's even happening.

A thread blocking or hanging at the wrong time is a much trickier condition to debug than an outright crash, so I chose to err on the side of "fail loud and early", and purposely fix any issues that pop up in the future, rather than risk silent misbehavior. This is especially true since you cannot set any of these flags "by mistake" (i.e. inadvertently through other libc funcs); you have to explicitly call `preadv2` (a glibc-only func) with `RWF_NOWAIT`, in which case I have to assume your code _really wants_ that behavior.

Eventually, once filesystems come into play, I plan to revisit meaningfully implementing `RWF_NOWAIT` to remove that error case.

> Should we use uk_pr_warn_once for RWF_SYNC, RWF_DYNC and RWF_APPEND also?

I don't think it is necessary; according to the manpage, those flags are indeed only _meaningful_ for `pwritev2`, but they are not disallowed in calls to `preadv2` (similar for `RWF_NOWAIT` for write). I think it's valid behavior to treat them as no-ops.

**Review by robertZamfir601 — APPROVED** [review]
I understand, sounds good to me.

Reviewed-by: Robert Zamfir <georobi.016@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
