### PR TITLE
lib/fdt: Cleanup and upgrade to 45f3d1a

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): arm / arm64
 - Platform(s): kvm
 - Application(s): N/A

### Additional configuration

None

### Description of changes

This series updates `lib/fdt` the latest state of libfdt from https://git.kernel.org/pub/scm/utils/dtc/dtc.git. At the time of writing, the latest change in `dtc/libfdt/` is `45f3d1a`.

This update effectively removes all changes made by Unikraft. In practice most changes had equivalent implementations upstream, except from one that is reverted. See below for details.

**IMPORTANT:** `lib/fdt` should be periodically updated from kernel.org. To minimize the maintenance effort, no changes must be made locally unless strictly required. Any work on libfdt should be upstreamed instead.

#### 4073ab7 Add "extern C" header to files
    
Implemented upstream.
    
#### 2def018 Introduce fdt_getprop_u32_by_offset helper
    
Moved to `plat/drivers/ofw/` with the rest of the helper functions.
    
#### e2833b8 Change the default value of fdt_size_cells

Implemented upstream.
    
#### 28fa775 Fix fdt_address_cell and fdt_size_cell
    
Traversing the tree to the root is incompatible with the device-tree
specification, which mandates looking at the immediate parent or using
the defaults. According to Sect 2.3.5 of the [device tree specification v0.3](https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.3):
```    
The #address-cells and #size-cells properties are not inherited from
ancestors in the devicetree. They shall be explicitly defined.
    
A DTSpec-compliant boot program shall supply #address-cells and #size-cells
on all nodes that have children.
    
If missing, a client program should assume a default value of 2 for
#address-cells, and a value of 1 for #size-cells.
```    
⚠️ This change is reverted

### CODE REVIEW

**Comment by michpappas** [comment]
Hi @justin-he, I'm CCing you here as you have been previously involved into this. Please notice the reverted change ⚠️ . Everything else should be backwards compatible :) Btw, it would be great if you upstreamed all the nice work you did in `plat/common/ofw`.

**Comment by razvand** [comment]
Thanks, @michpappas , this works. I rebased it to 0.8 and tested it against the [pl031 RTC driver](https://github.com/unikraft/unikraft/pull/316) and it works. For ARM32 I built a `linuxu` platform image and I included libfdt.

I will approve this after @razvanvirtan reviews it.

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Review by razvand — APPROVED** [review]

**Review by flpostolache — APPROVED** [review]
Looks good!

Reviewed-by: Florin Postolache <florin.postolache80@gmail.com>

**Review by razvand — APPROVED** [review]
All good.

Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
