### PR TITLE
.github/workflows: Enable -Werror on integration builds

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Additional configuration

None

### Description of changes

Add CONFIG_OPTIMIZE_WARNISERROR to the `self-test` and `helloworld` jobs to catch warnings introduced in PRs.

Exclude the `libc` job to avoid CI errors caused by warnings in the codebase of libmusl.

GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1298
GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1299
GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1300
GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1305
GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1306

### CODE REVIEW

**Comment by nderjung** [comment]
I am wondering if this should only be enabled once all warnings have been resolved?

**Comment by michpappas** [comment]
> I am wondering if this should only be enabled once all warnings have been resolved?

I was considering that if we merged this first it would force people to fix their warnings as all PRs would be blocked 😈  But in the end I decided to be nice and fix them myself. Cover letter updated with dependencies.

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Please merge when all problems are fixed.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by razvand** [comment]
@michpappas , only PR #1306 needs to be merged to let this PR to be merged as well. Once @oleksiimoisieiev and @andreistan26 take care of PR #1306, we will merge it and then merge this PR.

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
