### PR TITLE
lib/vfscore: Change `uk_syscall_e_open()` calls to `uk_syscall_r_open()`

### PR DESCRIPTION
**Pull request by eduardvintila**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [x86_64, arm]
 - Platform(s): [N/A]
 - Application(s): [app-redis]

### Description of changes

Raw syscalls implementations should always return the raw value. This PR fixes an incorrect calls to `open` in `openat` by replacing the `uk_syscall_e` variant with the `uk_syscall_r` raw implementation.

Signed-off-by: Eduard Vintilă <eduard.vintila47@gmail.com>

### CODE REVIEW

**Comment by StefanJum** [comment]
Thank you for this @eduardvintila.
Only one comment on the `creat` syscall. It uses the [`UK_SYSCALL_DEFINE` macro](https://github.com/unikraft/unikraft/blob/staging/lib/syscall_shim/include/uk/syscall.h#L194), that is based on [`UK_LLSYSCALL_DEFINE`](https://github.com/unikraft/unikraft/blob/staging/lib/syscall_shim/include/uk/syscall.h#L150), that returns `-1` on error and sets `errno`.
Should we keep using the `_e_` syscall variant there?

**Comment by eduardvintila** [comment]
Hi, @StefanJum. You're totally right, my bad for not catching this. Thanks a lot!

**Review by StefanJum — CHANGES_REQUESTED** [review]
One more thing @eduardvintila, we set `error = uk_syscall_r_open...` [here](https://github.com/unikraft/unikraft/pull/638/files#diff-50257766dd062f03b631cf9789a11b13c936be36b9423bca03ec8277b79264b0R208), but then the return value is `-error` [here](https://github.com/unikraft/unikraft/blob/73c294ee7c7d9707f23e8f03161e6542d1e8bb72/lib/vfscore/main.c#L213), so in case an error occurs when calling `syscall_r_open`, a positive value will be returned, and if the call succeeds then it will return a negative value instead of the new fd.
We should change the return value to `error`.

**Comment by eduardvintila** [comment]
You make a very good point, @StefanJum. It seems that the `open` syscall implementation already returns a negative value on error, which means that the negation applied at `return -error` [here](https://github.com/unikraft/unikraft/blob/73c294ee7c7d9707f23e8f03161e6542d1e8bb72/lib/vfscore/main.c#L213) is indeed redundant and will actually end up returning a negative value for a valid `fd`.

Thanks a lot, I don't know how this has surfaced just now, since I don't think this is tied to whether the call is made to the `syscall_r_open` or the `syscall_e_open` variant in the first place.

**Comment by StefanJum** [comment]
> Thanks a lot, I don't know how this has surfaced just now, since I don't think this is tied to whether the call is made to the `syscall_r_open` or the `syscall_e_open` variant in the first place.

@eduardvintila Yes it's definitely an old error and it's very strange we did not encounter it before, my guess is that since the libc wrapper uses the `uk_syscall_e_openat` variant [here](https://github.com/unikraft/unikraft/blob/56b71f484f49f1231cee708b1a37f27c2ea127f0/lib/vfscore/main.c#L229), `uk_syscall_r_openat` was just (almost) never used. It's still weird since the `_e_` version uses the `_r_` return value.

Taking another look, the implementation of the syscall still looks quite broken, since in case `fget` returns an error it behaves as the `uk_syscall_e_openat` should, it sets `errno` and returns `-1` [here](https://github.com/unikraft/unikraft/blob/56b71f484f49f1231cee708b1a37f27c2ea127f0/lib/vfscore/main.c#L192-L195), which should not be done, it should return the negative error code.

Sorry for the long chain of issues, hopefully this is the last one :)

**Comment by eduardvintila** [comment]
Yes, @StefanJum, I completely agree. It should not even set `errno` altogether. I've noticed a few other syscalls with this pattern, such as `fstatat`. I'll include a fix for `openat`, but fixes for other syscalls in `vfscore` I think should be part of a larger PR (which will probably include changes in calling the raw implementation of syscalls similar to this PR and #636).

**Review by StefanJum — APPROVED** [review]
Looks good now @eduardvintila, thank you,
Can you please create an issue stating that there are raw syscall implementations that set `errno` and give some examples like `fstatat`, so we can track the progress on that one?

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Comment by eduardvintila** [comment]
> Looks good now @eduardvintila, thank you, Can you please create an issue stating that there are raw syscall implementations that set `errno` and give some examples like `fstatat`, so we can track the progress on that one?

Will do, @StefanJum. Thank you for your **really** good observations!

**Review by razvand — APPROVED** [review]
This works. Thanks, @eduardvintila 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
