### PR TITLE
plat/common: A bunch of fixes post-merge of #1212

### PR DESCRIPTION
**Pull request by mogasergiu**
### Prerequisite checklist

 - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### Description of changes

A bunch of fixes post-merge of #1212

### CODE REVIEW

**Comment by razvand** [comment]
@mogasergiu , I still get this when building for and running with Firecracker:

```text
[    1.865866] Info: [libukboot] <boot.c @  500> Pre-init table at 0x16e100 - 0x16e100
[    1.869804] Info: [libukboot] <boot.c @  511> Constructor table at 0x16e100 - 0x16e100
[    1.873598] Info: [libukboot] <boot.c @  534> Calling main(2, ['http-c_fc-x86_64', 'template'])
[    1.877974] dbg:  [libposix_socket] <socket.c @  297> (int) uk_syscall_r_socket((int) 0x2, (int) 0x1, (int) 0x0)
[    1.882916] dbg:  [libukmpi] <mbox.c @   24> Created mailbox 0x314020
[    1.886021] dbg:  [libposix_socket] <socket.c @  429> (int) uk_syscall_r_bind((int) 0x0, (const struct sockaddr *) 0x11f10, (socklen_t) 0x10)
[    1.892400] dbg:  [libposix_socket] <socket.c @  692> (int) uk_syscall_r_listen((int) 0x0, (int) 0x1)
[    1.897076] dbg:  [libukmpi] <mbox.c @   34> Release mailbox 0x314020
[    1.900313] dbg:  [libukmpi] <mbox.c @   24> Created mailbox 0x313020
Listening on port 8080...
[    1.904866] dbg:  [libposix_socket] <socket.c @  411> (int) uk_syscall_r_accept((int) 0x0, (struct sockaddr *) 0x0, (socklen_t *) 0x0)
[    1.910901] CRIT: [libkvmplat] <lcpu.c @  383> Assertion failure: (((auxspcb_ptr->curr_fp) & ~((64)-1)) == (auxspcb_ptr->curr_fp))
[    1.916746] Info: [libkvmplat] <shutdown.c @   59> Unikraft halted
```

**Review by jschlumpp — APPROVED** [review]
Reviewed-by: Marco Schlumpp <marco@unikraft.io>

**Review by andreistan26 — APPROVED** [review]
Reviewed-by: Andrei Stan [andreistan2003@gmail.com](mailto:andreistan2003@gmail.com)

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
