### PR TITLE
build: Darwin (MacOS) support

### LINKED ISSUE #785: Native macOS/darwin support
### Feature request summary

This issue tracks enabling building Unikraft on macOS/darwin.  The changeset requires modifications to Unikraft's build system to accommodate for non-standard UNIX programs, e.g. `sed`, as well as enabling the runtime of Unikraft via QEMU on macOS.

### Describe alternatives

_No response_

### Related architectures

None

### Related platforms

None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by skuenzer**
This PR introduces native build support for Darwin environments (MacOS). The changes assume that the following packages are installed on the host via [Homebrew](https://brew.sh/):
```
brew install gnu-sed
brew install make
brew install m4
brew install gawk
brew install grep
brew install wget
brew install qemu
brew install socat
# ...for compiling x86_64 Unikernels
brew install x86_64-elf-binutils
brew install x86_64-elf-gcc
# ...for compiling aarch-64 Unikernels
brew install aarch64-elf-binutils
brew install aarch64-elf-gcc
```
Afterwards, the build system can be called via `gmake [make-target]` and `qemu-guest` should work as well.

### CODE REVIEW

**Comment by nderjung** [comment]
Hi, in commit 2557a75e0ff3ef3c74b2c13f7a9bd93cdf4dfbef, can you please address https://github.com/unikraft/unikraft/issues/1006 ? (I.e. adding to it replacing of `python` with `python3` in `env` requests?)

If this is possible via this commit, please can you include this line in the Git commit message:

```
GitHub-Fixes: #1006
```

**Review by nderjung — APPROVED** [review]
Aside from my one comment about addressing python3 changes in 645e06de44b22bca17861305f215c8494cabaa51 from #1006, this works for me! 🎉 

I tried it with KraftKit via:
```
git clone https://github.com/unikraft/app-helloworld.git;
cd app-helloworld;
mkdir .unikraft/;
cd .unikraft/;
git clone https://github.com/unikraft/unikraft.git;
cd unikraft;
gh pr checkout 1034;
cd ../..;
kraft build --no-pull --arch arm64 --plat qemu;
```

Reviewed-by: Alexander Jung <alex@unikraft.io>

**Review by Starnox — APPROVED** [review]
This is truly fantastic! Many people have been requesting this feature, and it functions flawlessly. I've tested it on both M1 and Intel Macs, and after a cursory examination of the code changes, I didn't find anything concerning. Combined with the PR from [lib-musl](https://github.com/unikraft/lib-musl/pull/70#event-10066029185), we should have fully developed support for Darwin.

Reviewed-by: Eduard-Florin Mihailescu [mihailescu.eduard@gmail.com](mailto:mihailescu.eduard@gmail.com)

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
