### PR TITLE
VFS re-arch fixes

### PR DESCRIPTION
**Pull request by skuenzer**
This PR adds several small fixes to the recently re-arch initiatives of `lib/vfscore` by the following PRs:
- #1171 
- #1183
- #1182
- #1179
- #1172 
- #1170 
- #1168
- #1165

Most importantly, this PR enables compiling with [`lib/musl`](https://github.com/unikraft/lib-musl/) again.

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
The changes in this pr look fine, but the `fcntl` call is still broken on calls that use `O_CLOEXEC` (this is the case for `nginx` and `redis`).

The `fcntl` call will reach the [`F_SETFD` case branch ](https://github.com/unikraft/unikraft/blob/staging/lib/posix-fdio/fd-shim.c#L304) and then return [`EINVAL` in `posix-fdtab`](https://github.com/unikraft/unikraft/blob/staging/lib/posix-fdtab/fdtab.c#L198).

We can merge the pr as it is if you think this error should be addressed in a different pr.

**Comment by skuenzer** [comment]
> The changes in this pr look fine, but the `fcntl` call is still broken on calls that use `O_CLOEXEC` (this is the case for `nginx` and `redis`).
> 
> The `fcntl` call will reach the [`F_SETFD` case branch ](https://github.com/unikraft/unikraft/blob/staging/lib/posix-fdio/fd-shim.c#L304) and then return [`EINVAL` in `posix-fdtab`](https://github.com/unikraft/unikraft/blob/staging/lib/posix-fdtab/fdtab.c#L198).
> 
> We can merge the pr as it is if you think this error should be addressed in a different pr.

Yes, we should address this in a separate PR. This PR mostly repairs compiling and configuring with the new VFS libraries. Since this is a new code base, there might be other things that are similarly affected. It was important to merge the re-arch early so that we can focus on stabilizing. It also introduces new important features, like unix domain sockets. If you have a fixes for occurring bugs, I'd kindly ask you to open a PR.

**Review by StefanJum — APPROVED** [review]
All good (#1195 should be merged, but it's not related).
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
Thanks @skuenzer, looks fine, works on `redis`. Before merging this, can you please fix the `interger` typo in commit 28b59fdee3dacfc89474cf8a14d5527e086af536? Other than that, all good on my side!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
