### PR TITLE
lib/vfscore: Export iftovt_tab

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration

 - `CONFIG_LIBVFSCORE=y`

### Description of changes

This is necessary for the public IFTOVT macro, which uses the symbol internally.

### CODE REVIEW

**Review by craciunoiuc — COMMENTED** [review]
Hey @mschlumpp 

Can you also add `vttoif_tab`? I can see that also that is used in macros and it's not exported.

**Comment by jschlumpp** [comment]
Done

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
