### PR TITLE
plat/kvm: Fix Kconfig dependency warning on Firecracker

### LINKED ISSUE #1498: `plat/kvm`: Kconfing dependency warning for Firecracker x86_64
### Describe the bug

When configuring a simple helloworld program with Firecracker on x86_64 either via `make defconfig` or via `make menuconfig`, the config system prints the warning below:

```text
WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
  Depends on [n]: LIBVIRTIO_MMIO [=n]
  Selected by [y]:
  - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])

WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
  Depends on [n]: LIBVIRTIO_MMIO [=n]
  Selected by [y]:
  - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])
```

The warning is appears because `VIRTIO_MMIO_LINUX_COMPAT_CMDLINE` is part of the `LIBVIRTIO_MMIO` menu entry (see [here](https://github.com/unikraft/unikraft/blob/staging/drivers/virtio/mmio/Config.uk#L25)), but that's not selected by [the Firecracker configuration](https://github.com/unikraft/unikraft/blob/staging/plat/kvm/Config.uk#L114)

### Steps to reproduce

Clone the [`maintainer-tools` repository](https://github.com/unikraft-upb/maintainer-tools), enter the `setups/c-helloworld/` directory, and run:

```console
UK_DEFCONFIG=$(pwd)/defconfig.fc.x86_64 make defconfig
```

Or, while in the `setups/c-helloworld/` directory, run `make menuconfig`. When selecting Firecracker from the menu, the warning is appears briefly on the screen.

### Expected behavior

No warning message should be printed in the configuration step.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
  Depends on [n]: LIBVIRTIO_MMIO [=n]
  Selected by [y]:
  - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])

WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
  Depends on [n]: LIBVIRTIO_MMIO [=n]
  Selected by [y]:
  - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])
```

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`x86_64`]
 - Platform(s): [`kvm`]
 - Application(s): [N/A]

### Description of changes

Fix dependency warnings about VIRTIO_MMIO on Firecracker when no devices are selected.
```
WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
   Depends on [n]: LIBVIRTIO_MMIO [=n]
   Selected by [y]:
   - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])

 WARNING: unmet direct dependencies detected for VIRTIO_MMIO_LINUX_COMPAT_CMDLINE
   Depends on [n]: LIBVIRTIO_MMIO [=n]
   Selected by [y]:
   - KVM_VMM_FIRECRACKER [=y] && <choice> && (ARCH_X86_64 [=y] || ARCH_ARM_64 [=n])
```

GitHub-Fixes: #1498

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Works.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Review by thass0 — APPROVED** [review]
Looks good

Reviewed-by: Thassilo Schulze <thassilo@thasso.xyz>

**Review by skuenzer — APPROVED** [review]
Approved-by: Simon Kuenzer <simon@unikraft.io>

**Pull request merged**
