### PR TITLE
lib/uksglist: Fix for Issue #730

### PR DESCRIPTION
**Pull request by vineethkm**
Add __nonnull keyword to suitable function declarations in lib/uksglist library.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [ ] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Description of changes
Add __nonnull macro to suitable function declarations in lib/uksglist library.

### CODE REVIEW

**Comment by vineethkm** [comment]
Do I have to make the suggested changes by checkpatch.pl? Also do I have to add the __nonnull macro to functions that have UK_ASSERT in their definitions?

**Comment by nderjung** [comment]
Hi @vineethkm, thank you for your contribution! I suggest to update your commit message to the following:

```
lib/uksglist: Add `__nonnull` to relevant `uk_sglist_*` methods

GitHub-Fixes: #730
Signed-off-by: ...etc...
```

Regarding the greater than 80 character length, this is a question regarding style for @razvand as I am unsure, there is a manual being prepared with new coding conventions and Razvan will know the latest requirements.

**Comment by nderjung** [comment]
Hi @vineethkm, you need to delete the first line of the commit message, i.e. `lib/uksglist: Fix for Issue #730`.

**Review by StefanJum — APPROVED** [review]
Looks good to me @vineethkm, thanks. I'll add the review tag after @nderjung takes another look.

**Comment by razvand** [comment]
@nderjung, I think it's OK to break the `80` character requirement for this case. If all OK, please approve this PR.

**Comment by nderjung** [comment]
I've been out of the recent styling discussions so will OK based on @razvand's recommendation. It all looks good otherwise.

@StefanJum you can add your tag, I'll do the approval once updated.

**Review by StefanJum — APPROVED** [review]
Do your magic @nderjung.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by nderjung — APPROVED** [review]
Thanks!

Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request closed without merging**
