### PR TITLE
Fix various warnings

### PR DESCRIPTION
**Pull request by marcrittinghaus**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

This PR fixes various warnings due to unused variables and arguments.

### CODE REVIEW

**Comment by razvand** [comment]
@marcrittinghaus , @mschlumpp , I assigned myself as a reviewer, I'm doing a quick pass now.

**Comment by mschlumpp** [comment]
Looks good to me. 
Reviewed-by: Marco Schlumpp <marco@unikraft.io>

@razvand Do you any comments on this PR? Otherwise, you can approve it.

**Review by jschlumpp — APPROVED** [review]
Looks good to me.
Reviewed-by: Marco Schlumpp <marco@unikraft.io>

@razvand Do you any comments on this PR? Otherwise, you can approve it.

**Comment by razvand** [comment]
> Looks good to me. Reviewed-by: Marco Schlumpp [marco@unikraft.io](mailto:marco@unikraft.io)
> 
> @razvand Do you any comments on this PR? Otherwise, you can approve it.

Doing the final checks now, before approving.

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
