### PR TITLE
plat: Migrate ns16550 to drivers/uktty

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [ ] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [N/A]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

Migrate the NS16550 driver to `drivers/uktty`

GitHub-Depends-On: https://github.com/unikraft/unikraft/pull/1025

### CODE REVIEW

**Comment by michpappas** [comment]
Notice that the driver is introduced as a platform library, ie:
```
$(eval $(call addplatlib_s,kvm,libuktty_ns16550,$(CONFIG_LIBUKTTY_NS16550)))
```
This is due to limitations of https://github.com/unikraft/unikraft/pull/1023. **Do not merge until resolved.**

**Comment by michpappas** [comment]
Changes in this update:
- Rebase to latest state of #1023
- Replace subsystem's `Config.uk` `menuconfig` with `menu`
- Register library using `addlib_s`
- Add `exportsyms.uk`
- Add `ASINCLUDES` and `CXXINCLUDES`

**Review by razvanvirtan — APPROVED** [review]
Hi, @michpappas!
Things look good to me, thanks!
Just a few typos to be solved in the commit messages:

- https://github.com/unikraft/unikraft/pull/1026/commits/6e69aec092ae588ece25dd695d678042ed0a7121 `Migrane`
- https://github.com/unikraft/unikraft/pull/1026/commits/f817f56bc24f2aff66ac05babbc6d308e32267c7 `standand library`
- https://github.com/unikraft/unikraft/pull/1026/commits/f817f56bc24f2aff66ac05babbc6d308e32267c7 `drivers` (I think the plural should be used in the selector)

Reviewed-by: Razvan Virtan <virtanrazvan@gmail.com>

**Review by Starnox — APPROVED** [review]
Looks good!

Reviewed-by: Eduard-Florin Mihailescu [mihailescu.eduard@gmail.com](mailto:mihailescu.eduard@gmail.com)

**Review by rares-miculescu — APPROVED** [review]
All good!

Reviewed-by: Rares Miculescu [miculescur@gmail.com](mailto:miculescur@gmail.com)

**Comment by michpappas** [comment]
@razvanvirtan thanks, all typos are fixed now.

**Comment by michpappas** [comment]
Added one more commit to use `unlikely` in error conditions similarly to the `pl011` PR.

**Review by mogasergiu — APPROVED** [review]
Reviewed-by: Sergiu Moga <sergiu.moga@unikraft.io>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
