### PR TITLE
lib/nolibc: Fix & improve headers

### PR DESCRIPTION
**Pull request by andreittr**
### Description of changes

This PR addresses a couple of shortcomings in the headers provided with nolibc:
- Fix typo of `CHAR_BIT` being spelled as `CHAR_BITS`
- Add missing integer literal macros to `stdint.h`
- Add missing floating point constant headers (`float.h` + dependencies)

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### CODE REVIEW

**Comment by DeliaPavel** [comment]
Looks good to me! It seems like the checkpatch failed, but I am ready to approve once it passes.

**Comment by andreittr** [comment]
> Looks good to me! It seems like the checkpatch failed, but I am ready to approve once it passes.

I believe it's a case of a false positive from a heuristic script: the values of the macros aren't "complex", rather very plain float literals in scientific notation. The '+' must be confusing the script's regexes, but it won't confuse the compiler's lexer.
Regardless, in cases where we import files as-is from upstream projects as opposed to writing new code (like here from musl) I think avoiding unnecessary changes is worthwhile.

**Review by DeliaPavel — APPROVED** [review]
Reviewed-by: Delia Pavel <delia_maria.pavel@stud.acs.upb.ro>

**Review by StefanJum — CHANGES_REQUESTED** [review]
This looks fine @andreittr, please rebase it on top of staging so the ci/cd tests can run.

**Comment by razvand** [comment]
@StefanJum, see this. The `checkpatch` items can be ignored, they're basically issues with the way checkpatch works. After you approve it, I'll cast the final approve.

**Review by StefanJum — APPROVED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
