### PR TITLE
lib/ukstore: Introduce the ukstore library (dynamic)

### PR DESCRIPTION
**Pull request by craciunoiuc**
These commits introduce a new internal library to Unikraft, ukstore.
The role of this new library is to provide a standard way of passing
information getters/setters from one place to another.

The function pointers are stored in entries and entries are stored in
folders. These are structured in two different ways, statically and
dynamically. The dynamic ones can be added and deleted at runtime
and they are structured differently (section array of folders vs. list
of folders).

To generate sections per library the AWK tool is used together with
the build system. This library has a dependency only to nolibc.

This PR does not depend on any other `ukstore` PR, but it will have
to be rebased after #459 is in. The old PR was marked as Draft.

Signed-off-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

### CODE REVIEW

**Comment by craciunoiuc** [comment]
@skuenzer we will continue our discussion here. This can/should make it this release

I have 2 things I will comment upon because I'm not sure about them.
Also, please do a full pass over it, because I had to reorder the commits and I hope I didn't mess something (it works).

also tagging: @marcrittinghaus @nderjung @mandrei12

**Comment by craciunoiuc** [comment]
Hey @skuenzer @mandrei12,

I rebased this PR and it's all yours. I'll look into splitting `uklibid` soon.

**Comment by mandrei12** [comment]
Looks good to me. @skuenzer, could you take a look?

**Comment by gabrielmocanu** [comment]
@skuenzer  any updates on this?

**Comment by craciunoiuc** [comment]
Closed in favor of #939

**Pull request closed without merging**
