### PR TITLE
plat/common/arm: Add ISB after enabling PAuth()

### PR DESCRIPTION
**Pull request by michpappas**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [`arm64`]
 - Platform(s): [N/A]
 - Application(s): [N/A]

### Description of changes

Add an ISB at the end of pauth_init() to ensure that all writes to system control registers have completed.

### CODE REVIEW

**Review by mogasergiu — APPROVED** [review]
LGTM.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Review by andreistan26 — APPROVED** [review]
Looks good.

Reviewed-by: Andrei Stan [andreistan2003@gmail.com](mailto:andreistan2003@gmail.com)

**Review by mariasfiraiala — APPROVED** [review]
Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
