### PR TITLE
lib/uksignal: update sigset_t macros

### PR DESCRIPTION
**Pull request by bernirz**
Update the macro affecting bit manipulation of sigset_t

### CODE REVIEW

**Comment by nderjung** [comment]
Hi! Thanks for the PR :)

Please can you check you have `Signed-off-by` your commits (`git commit -s` should do the trick) and address the errors in the checkpatch.  Do not worry about the configure errors in the checks section, I am addressing these in the mean time with a seperate code issue and will re-trigger the CI checks.

**Review by nderjung — COMMENTED** [review]
Hi @bernirz,

Thanks again for this PR.  Please can you give a little bit more context to this change; i.e. why you are making this change?

Please can you also fix the checkpatch, squashing the commits and providing said same description of change in the commit message.  Please also don't forget to sign-off! :)

Thanks again 🐒

**Comment by razvand** [comment]
@dragosargint created a new PR.

**Comment by razvand** [comment]
This has been resubmitted by @dragosargint in #326

**Pull request closed without merging**
