### PR TITLE
lib/posix-time*: Replace time syscalls with internal API

### PR DESCRIPTION
**Pull request by andreittr**
### Description of changes

This changeset exposes the syscalls provided by `posix-time` as Unikraft-internal API (`uk_sys_*`), allowing internal components to bypass the binary syscall interface.
Furthermore, `posix-timerfd` is patched to use this internal API in lieu of syscalls.

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): N/A
 - Platform(s): N/A
 - Application(s): N/A

### Additional configuration
N/A

### CODE REVIEW

**Comment by Mihnea0Firoiu** [comment]
When I try to run applications from the catalog I get the following output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17c02ce]

goroutine 873 [running]:
kraftkit.sh/manifest.(*manifestManager).Catalog(0xc00013db20, {0x21d1a38, 0xc000a89dd0}, {0xc00062d890, 0x6, 0x6?})
        /__w/kraftkit/kraftkit/manifest/manager.go:302 +0x4ee
kraftkit.sh/packmanager.UmbrellaManager.Catalog({0xc00062d350?, 0xc00062d320?, 0xc00062d2f0?}, {0x21d1a38, 0xc000a89dd0}, {0xc00062d890, 0x6, 0x6})
        /__w/kraftkit/kraftkit/packmanager/umbrella.go:169 +0x128
kraftkit.sh/internal/cli/kraft/build.(*builderKraftfileUnikraft).pull.func3({0x21d1a38, 0xc000a89dd0})
        /__w/kraftkit/kraftkit/internal/cli/kraft/build/builder_kraftfile_unikraft.go:243 +0x3d6
kraftkit.sh/tui/processtree.(*ProcessTree).Init.(*ProcessTree).waitForProcessCmd.func2()
        /__w/kraftkit/kraftkit/tui/processtree/processtree.go:329 +0xb4
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:294 +0x29
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 922
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:293 +0x139
```
Am I the only one encountering this problem?

**Review by Mihnea0Firoiu — APPROVED** [review]
All good!
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

**Review by RaduNichita — APPROVED** [review]
Looks good to me.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

**Review by adinamariav — APPROVED** [review]

**Review by adinamariav — APPROVED** [review]
Looks good.
Reviewed-by: Adina-Maria Vaman adinamariav22@gmail.com

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
