### PR TITLE
arch/x86: Introduce NMI event for x86

### PR DESCRIPTION
**Pull request by jschlumpp**
### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [x] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `kvm`
 - Application(s): N/A

### Description of changes

This allows libraries to handle NMI interrupts.

### CODE REVIEW

**Comment by razvand** [comment]
@mschlumpp, this is OK with me. I'll wait for @mogasergiu's and @RaduNiculae's review, and then I'll do the final approval step.

**Review by mogasergiu — APPROVED** [review]
LGTM.

Reviewed-by: Sergiu Moga <sergiu@unikraft.io>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Review by RaduNiculae — APPROVED** [review]
Looks good!

**Pull request closed without merging**
