### PR TITLE
doc: Add Codacy code quality status badge to README.md

### LINKED ISSUE #650: Add code quality status badge to `README.md`
### Feature request summary

This issue tracks the addition of a code quality badge to the main `README.md`.

```
[![Codacy Badge](https://app.codacy.com/project/badge/Grade/454f62251d96413fac8024b28df2ce5b)](https://www.codacy.com/gh/unikraft/unikraft/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=unikraft/unikraft&amp;utm_campaign=Badge_Grade)
```

Will result in:

[Codacy Badge](https://www.codacy.com/gh/unikraft/unikraft/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=unikraft/unikraft&amp;utm_campaign=Badge_Grade)

### Describe alternatives

_No response_

### Related architectures

_No response_

### Related platforms

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by v-aryan**
addition of a code quality badge to the main README.md

Changes Made:
[Codacy Badge](https://www.codacy.com/gh/unikraft/unikraft/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=unikraft/unikraft&amp;utm_campaign=Badge_Grade)

### CODE REVIEW

**Comment by craciunoiuc** [comment]
I am okay with this.

@nderjung ?

**Review by craciunoiuc — CHANGES_REQUESTED** [review]
Hey @aryanvarma7272,

Thanks a lot for your submission.

A few comments:
 1. Can you break the changes into 2 commits, one that adds the badge, and one that removes old links. Also I saw that some of the links still work, so not sure if we should remove them.
 2. Can you add the signed-off tag to your comments, as per the contributor guideline

**Comment by nderjung** [comment]
Hi @aryanvarma7272 any update on this? Please see Cezar's suggestions.  Additionally, i would phrase the commit title:
```
doc: Add code quality status badge to README.md
```

**Comment by nderjung** [comment]
Hi, I've force-pushed to the branch which incorporate necessary changes for this PR to be approved since there was no response back from OP.

Handing it over to you @razvand to have a look.

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by razvand — APPROVED** [review]
Looks good. Thanks, @nderjung , @aryanvarma7272 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
